L = load('/home/data/2001-07-31/analysis/scratch/ME_tet1_0001_master','-mat');
L2 = load('/home/data/2001-07-31/analysis/scratch/ME_tet1_0001_','-mat');
L3 = load('/home/data/2001-07-31/analysis/scratch/ME_tet1_0001_t00001_','-mat');

figure(1);
  i__ = 1;
for i=interval,
  subplot(10,10,i__);
  plotcsp(L.csp(:,i));
  LL=L.stime(L.idx(i));
  LLL=int2str(LL);
  title([LLL ':' int2str(L.stype(L.idx(i)))]);% ':' int2str(L.idx(i))]);
  set(gca,'xtick',[]);
     %'set(get(findobj(2,''type'',''axes''),''title''),''String'',int2str(idx(i)));' ...
     %'set(get(get(3,''Children''),''title''),''String'',int2str(idx(i)));' ...
  set(gca,'ButtonDownFcn',...
   ['set(findobj(2,''type'',''axes''),''xlim'',' LLL '+[-100 100],''ylim'',[-4 2]);' ...
  'set(2,''userdata'',' int2str(i) '); ' ...
  'set(get(3,''Children''),''xlim'',' LLL '+[-100 100],''ylim'',[-1 300]);' ...
  'if exist(''bar1'')&ishandle(bar1),delete(bar1);end;if exist(''bar2'')&ishandle(bar2),delete(bar2);end;' ...
  'axes(findobj(2,''Type'',''Axes''));bar1=plot([' LLL ' ' LLL '],[-4 2],''k'');' ...
  'axes(get(3,''Children''));bar2=plot([' LLL ' ' LLL '],[-1 300],''k'');']);
  i__ = i__ + 1;
end;

