function fig = admin_db( db )
%ADMINL_DB control panel for database
%
%  H_FIG = ADMIN_DB( DB )
%
%    DB can be a structarray or a filename
%
%
%  For normal database use, use CONTROL_DB instead
%
%  2012, Alexander Heimel
%

if nargin<1
    h_fig = control_db;
else
    h_fig = control_db(db);
end

if isempty(h_fig)
    return
end

if nargout==1
    fig = h_fig;
end

set(h_fig,'Name','Database administration');




p = get(h_fig,'Position');
p(3) = p(3)+80;
set(h_fig,'Position',p);

% extra buttons:

left=10;
buttonwidth=70;
colsep=3;
buttonheight=30;
top=10;

ud=get(h_fig,'UserData');
h=ud.h;
set(ud.record_form,'CloseRequestFcn','closereq');

maxleft = 0;

h.addtextfield = ...
    uicontrol('Parent',h_fig, ...
    'Units','pixels', ...
    'BackgroundColor',0.8*[1 1 1],...
    'Callback',['fig=gcf;ud=get(fig,''userdata'');[ud.db,suc]=add_field(ud.db,'''');'...
    'if ~suc;return;end;'...
    'p=get(ud.record_form,''position'');'...
    'close(ud.record_form);'...
    'ud.record_form=[];'...
    'ud.changed=1;'...
    'set(fig,''userdata'',ud);'...
    'control_db_callback(ud.h.current_record);'...
    'ud=get(fig,''userdata'');'...
    'pn=get(ud.record_form,''position'');pn([1 2])=p([1 2])-pn([3 4])+p([3 4]);'...
    'set(ud.record_form,''position'',pn);'  ] ,...
    'ListboxTop',0, ...
    'Position',[left top buttonwidth+30 buttonheight], ...
    'String','Add text field' );
left=left+buttonwidth+30+colsep;
maxleft=max(maxleft,left);

h.addnumericfield = ...
    uicontrol('Parent',h_fig, ...
    'Units','pixels', ...
    'BackgroundColor',0.8*[1 1 1],...
    'Callback',['fig=gcf;ud=get(fig,''userdata'');[ud.db,suc]=add_field(ud.db,[]);'...
    'if ~suc;return;end;'...
    'p=get(ud.record_form,''position'');'...
    'close(ud.record_form);'...
    'ud.record_form=[];'...
    'ud.changed=1;'...
    'set(fig,''userdata'',ud);'...
    'control_db_callback(ud.h.current_record);'...
    'ud=get(fig,''userdata'');'...
    'pn=get(ud.record_form,''position'');pn([1 2])=p([1 2])-pn([3 4])+p([3 4]);'...
    'set(ud.record_form,''position'',pn);'  ] ,...
    'ListboxTop',0, ...
    'Position',[left top buttonwidth+40 buttonheight], ...
    'String','Add num. field' );
left=left+buttonwidth+40+colsep;
maxleft=max(maxleft,left);


h.removefield = ...
    uicontrol('Parent',h_fig, ...
    'Units','pixels', ...
    'BackgroundColor',0.8*[1 1 1],...
    'Callback',['fig=gcf;ud=get(fig,''userdata'');[ud.db,suc]=remove_field(ud.db);'...
    'if ~suc;return;end;'...
    'p=get(ud.record_form,''position'');'...
    'close(ud.record_form);'...
    'ud.record_form=[];'...
    'ud.changed=1;'...
    'set(fig,''userdata'',ud);'...
    'control_db_callback(ud.h.current_record);'...
    'ud=get(fig,''userdata'');'...
    'pn=get(ud.record_form,''position'');pn([1 2])=p([1 2])-pn([3 4])+p([3 4]);'...
    'set(ud.record_form,''position'',pn);'  ] ,...
    'ListboxTop',0, ...
    'Position',[left top buttonwidth+40 buttonheight], ...
    'String','Remove field' );
left=left+buttonwidth+40+colsep;
maxleft=max(maxleft,left);




h.reorderfields = ...
    uicontrol('Parent',h_fig, ...
    'Units','pixels', ...
    'BackgroundColor',0.8*[1 1 1],...
    'Callback',['fig=gcf;ud=get(fig,''userdata'');[ud.db,suc]=reorder_fields(ud.db);'...
    'if ~suc;return;end;'...
    'p=get(ud.record_form,''position'');'...
    'close(ud.record_form);'...
    'ud.record_form=[];'...
    'ud.changed=1;'...
    'set(fig,''userdata'',ud);'...
    'control_db_callback(ud.h.current_record);'...
    'ud=get(fig,''userdata'');'  ...
    'set(ud.record_form,''position'',p);'  ] ,...
    'ListboxTop',0, ...
    'Position',[left top buttonwidth+40 buttonheight], ...
    'String','Reorder fields' );
left=left+buttonwidth+40+colsep;
maxleft=max(maxleft,left);

h.renamefield = ...
    uicontrol('Parent',h_fig, ...
    'Units','pixels', ...
    'BackgroundColor',0.8*[1 1 1],...
    'Callback',['fig=gcf;ud=get(fig,''userdata'');[ud.db,suc]=rename_field(ud.db);'...
    'if ~suc;return;end;'...
    'p=get(ud.record_form,''position'');'...
    'close(ud.record_form);'...
    'ud.record_form=[];'...
    'ud.changed=1;'...
    'set(fig,''userdata'',ud);'...
    'control_db_callback(ud.h.current_record);'...
    'ud=get(fig,''userdata'');'  ...
    'set(ud.record_form,''position'',p);'  ] ,...
    'ListboxTop',0, ...
    'Position',[left top buttonwidth+40 buttonheight], ...
    'String','Rename field' );
left=left+buttonwidth+40+colsep;
maxleft=max(maxleft,left);

% make figure wide enough
pos=get(h_fig,'Position');
pos(3)=max(maxleft,pos(3));
set(h_fig,'Position',pos);



ud.h=h;
set(h_fig,'UserData',ud);



