function newparams = browse_data(theme,cksds)

%L = load(fname,'-mat');

p0 = getparameters(theme);
h0 = buildwindow(theme,cksds);
ud = get(h0,'userdata');
  % initialize
set(h0,'userdata',ud);

p0 = getparameters(theme);
updatefields(h0,theme);
plotspikes(h0,0);
plotfeatures(h0,1);


zoom on;
done = 0;
while ~done,
  uiwait(h0);
  o = get(findobj(h0,'Tag','okbt'),'userdata');
  ud = get(h0,'userdata');
  if strcmp(get(o,'Tag'),'Axes'),

  else,
     name = get(o,'Tag'); disp(name);
         if strcmp(name,'forward'),  plotspikes(h0,1);
     elseif strcmp(name,'forend'),   plotspikes(h0,Inf);
     elseif strcmp(name,'backward'), plotspikes(h0,-1);
     elseif strcmp(name,'backend'),  plotspikes(h0,-Inf);
     elseif strcmp(name,'featuremenu'), setfeatures(h0);
     elseif strcmp(name,'spclickmenu'),
         disp('this is spclickmenu');
         switch get(o,'value'),
            case 1, zoom on;
            case 2, zoom off;
         end;
     elseif strcmp(name,'SpikeAxes'),
         disp('this is spikeaxes');
         ud.currspike = get(o,'userdata');
         set(h0,'userdata',ud);
         drawcurrentspike(h0,p0);
     elseif strcmp(name,'okbt'),
         newparams = checkinput(h0,p0);
         if ~isempty(newparams),
	         done=1;
	 end;
     elseif strcmp(name,'Cancelbt'),
         newparams = p0;
         done=1;
     elseif strcmp(name,'HelpBt'),
         textbox('multiextractor help',help('multiextractor'));
     elseif strcmp(name,'OpenDataBt'),
         getdata(h0);
         extractspikes(h0,p0);
         plotspikes(h0,0)
     elseif (strcmp(name,'thresh')|strcmp(name,'thresh2')|strcmp(name,'thresh3')|...
            strcmp(name,'threshcov')|strcmp(name,'directionmenu')|strcmp(name,'filtertypemenu')|...
            strcmp(name,'filterarg')|strcmp(name,'remove_unresolvedmenu')|...
            strcmp(name,'useabsmenu')|strcmp(name,'normalizemenu')|strcmp(name,'oversampling')|...
            strcmp(name,'peak_sep')|strcmp(name,'post_time')|strcmp(name,'pre_time')|...
            strcmp(name,'event_sep')|strcmp(name,'overlap_sep')),
         p = checkinput(h0,p0);
         if ~isempty(p),
            extractspikes(h0,p0); plotspikes(h0,0);
         end;
     end;
  end;
end;

delete(h0);

function getdata(h0)  % sets userdata if successful
ud = get(h0,'userdata');
if isa(ud.cksds,'cksdirstruct'),
  g = getallnamerefs(ud.cksds); str = {};
  for i=1:length(g), str{i}= [g(i).name ' | ' int2str(g(i).ref) ]; end;
  [s,v]=listdlg('PromptString','Select a record','SelectionMode','single','ListString',str);
  if isempty(s), return; end;
  recstr = gettests(ud.cksds,g(s).name,g(s).ref);
  [sr,vr]=listdlg('PromptString','Select a record','SelectionMode','single','ListString',recstr);
  if isempty(sr), return; end;
  cksmd = cksmeasureddata(getpathname(ud.cksds),g(s).name,g(s).ref,[],[]);
  ints = get_intervals(cksmd); ints = ints(sr,:); n = round(diff(ints)/10),
  stri={}; for i=1:n, stri{i} = int2str(i); end;
  [si,vi]=listdlg('PromptString','Which repetitions (must be consecutive)',...
       'SelectionMode','multiple','ListString',stri);
  if isempty(si), return; end;
  interval = ints(1)+[10*(si(1)-1) 10*(si(end))];
  ud.data.data = cksmd; ud.data.interval = [interval(1) interval(2)],
  set(h0,'userdata',ud);
else,
  errordlg('Cannot select multiunit data w/o valid cksdirstruct.');
end;

function extractspikes(h0,p0)

p = checkinput(h0,p0)
ud = get(h0,'userdata');
if isempty(p),
  ud.spikes = [];
else,
  me = multiextractor(p); t = ud.data.interval(1);
  [h,Tt]=get_data(ud.data.data,[t t+10],2); h = h';
  h(1,:) = mefilter(me,h(1,:)); h(2,:) = mefilter(me,h(2,:));  % from setup.m
  h(3,:) = mefilter(me,h(3,:)); h(4,:) = mefilter(me,h(4,:));
  h = h';
  stddev = std(h); m = mean(h);
  he = h - repmat(m,size(h,1),1);         % subtract mean
  he = he./repmat(stddev,size(h,1),1); % normalize
  he = sum(he'.^2)';                    % energy
  z = findcovdata(he,p0.threshcov,max(1,floor((p0.pre_time+p0.post_time)/(Tt(2)-Tt(1)))));
  thecov = cov(h(z,:));
  % do first loop
  [stime,stype,csp,cest,idx] = muex(me,h,thecov,Tt(2)-Tt(1));
  stime = stime(idx); stype = stype(idx);
  ttime = (stime-1)*(Tt(2)-Tt(1))+t;
  for t=ud.data.interval(1)+10:10:ud.data.interval(2)-10,
    [h,Tt] = get_data(ud.data.data,[t t+10-(Tt(2)-Tt(1))],2); h = h';
      h(1,:) = mefilter(me,h(1,:)); h(2,:) = mefilter(me,h(2,:));
      h(3,:) = mefilter(me,h(3,:)); h(4,:) = mefilter(me,h(4,:));
      h = h';
      [sti_t,sty_t,csp_t,cest_t,idx_t] = muex(me,h,thecov,Tt(2)-Tt(1));
      ttime_t = (sti_t(idx_t)-1)*(Tt(2)-Tt(1))+t;
      stime = cat(1,stime,sti_t(idx_t)); stype = cat(1,stype,sty_t(idx_t));
      csp = cat(2,csp,csp_t); cest=cat(1,cest,cest_t); idx = cat(1,idx,idx_t);
      ttime = cat(1,ttime,ttime_t);
  end;
  ud.spikes=csp;ud.cest=cest;ud.stime=stime;ud.stype=stype;ud.idx=idx;ud.ttime=ttime;
  ud.currspike = 1; ud.thecov = thecov; ud.spikeloc = ceil(p.pre_time/(Tt(2)-Tt(1))) + 1;
  set(h0,'userdata',ud);
  drawcurrentspike(h0,p0); setfeatures(h0);
end;

function drawcurrentspike(h0,p0)
p = checkinput(h0,p0);
ud = get(h0,'userdata');
if ~isempty(ud.currspike),
   disp('drawing current spike.');
   t = ud.ttime(ud.currspike);
   tsmint = [t-2*p.pre_time t+2*p.post_time]; tlgint = [t-0.100 t+0.100];
   [dat_sm,tt_sm] = get_data(ud.data.data,tsmint,2);
   [dat_lg,tt_lg] = get_data(ud.data.data,tlgint,2);
   ax = gca;

   axes(findobj(h0,'Tag','zoom_raw')); hold off;
   plot(tt_sm,dat_sm); hold on;
   indssm = find(ud.ttime>=tsmint(1)&ud.ttime<=tsmint(2));
   samp_dt = tt_sm(2)-tt_sm(1); sampssm = round(1+(-tt_sm(1)+ud.ttime(indssm))/samp_dt);
   size(dat_sm(sampssm,:))
   plot(ud.ttime(indssm),dat_sm(sampssm,:),'bo');
   %drawnow;
   axi=axis, axi(3),axi(4),ydiff=axi(4)-axi(3);
   plot([t-p.peak_sep t-p.peak_sep],[axi(3)-5*ydiff axi(4)+5*ydiff],'b');
   plot([t+p.peak_sep t+p.peak_sep],[axi(3)-5*ydiff axi(4)+5*ydiff],'b');
   plot([t-p.overlap_sep t-p.overlap_sep],[axi(3)-5*ydiff axi(4)+5*ydiff],'g');
   plot([t+p.overlap_sep t+p.overlap_sep],[axi(3)-5*ydiff axi(4)+5*ydiff],'g');
   plot([t-p.event_sep t-p.event_sep],[axi(3)-5*ydiff axi(3)+5*ydiff],'r');
   plot([t+p.event_sep t+p.event_sep],[axi(3)-5*ydiff axi(3)+5*ydiff],'r');
   plot([t t],[axi(3)-5*ydiff axi(4)+5*ydiff],'k');
   set(gca,'xlim',tsmint,'xtick',[],'ylim',[axi(3) axi(4)],'Tag','zoom_raw'); 

   axes(findobj(h0,'Tag','full_raw')); hold off;
   plot(tt_lg,dat_lg);  hold on;
   indslg = find(ud.ttime>=tlgint(1)&ud.ttime<=tlgint(2));
   samp_dt = tt_sm(2)-tt_sm(1); sampslg = round(1+(-tt_lg(1)+ud.ttime(indslg))/samp_dt);
   plot(ud.ttime(indslg),dat_lg(sampslg,:),'bo');
   hold on;
   axi = axis;  ydiff = axi(4)-axi(3);
   plot([t t],[axi(3)-5*ydiff axi(4)+5*ydiff],'k');
   set(gca,'xlim',tlgint,'xtick',[],'ylim',[axi(3) axi(4)],'Tag','full_raw');

   axes(findobj(h0,'Tag','zoom_energy'));
   [e,e_pos,e_neg] = findenergy(h0,p0,dat_sm);
   hold off; plot(tt_sm,e,'b'); hold on; plot(tt_sm,e_pos,'r'); plot(tt_sm,e_neg,'g');
   plot(ud.ttime(indssm),e(sampssm),'bo');
   plot(tsmint,[p.thresh p.thresh],'b'); plot(tsmint,[p.thresh2 p.thresh2],'r');
   plot(tsmint,[p.thresh3 p.thresh3],'k'); plot(tsmint,[p.threshcov p.threshcov],'g');
   set(gca,'xlim',tsmint','Tag','zoom_energy');

   axes(findobj(h0,'Tag','full_energy'));
   [e,e_pos,e_neg] = findenergy(h0,p0,dat_lg);
   hold off; plot(tt_lg,e,'b'); hold on; plot(tt_lg,e_pos,'r'); plot(tt_lg,e_neg,'g');
   plot(ud.ttime(indslg),e(sampslg),'bo');
   plot(tlgint,[p.thresh p.thresh],'b'); plot(tlgint,[p.thresh2 p.thresh2],'r');
   plot(tlgint,[p.thresh3 p.thresh3],'k'); plot(tlgint,[p.threshcov p.threshcov],'g');
   set(gca,'xlim',tlgint','Tag','full_energy');

   axes(gca);
end;

function [e,e_pos,e_neg] = findenergy(h0,p0,data);

p = checkinput(h0,p0);
ud = get(h0,'userdata');
if isempty(p), e=[]; e_pos=[]; e_neg=[];
else,
   % now importing from muex.m
   switch p.normalize,
       case 0, V=diag(diag(ones(4))); D = diag(diag(ones(4)));
       case 1, [V,D] = eig(ud.thecov);
       case 2, [V,D] = eig(diag(diag(ud.thecov)));
   end;
   T = V*sqrt(inv(D));
   m = mean(data);
   data = data - repmat (m, size (data, 1), 1);
   e = sum((data*T)'.^2);
   e_pos = sum((data.*(data>0)*T)'.^2);
   e_neg = sum((data.*(data<0)*T)'.^2);
end;


function setfeatures(h0)  % sets userdata
ud = get(h0,'userdata');
switch get(findobj(h0,'Tag','featuremenu'),'value'),
   case 1, % peaks
      ud.fea = wdc_extractPeaks(ud.spikes,ud.spikeloc,1); % need to get data dir IMP
   case 2, % values at max energy
      ud.fea = wdc_extractRaw(ud.spikes,ud.spikeloc)';
end;
set(h0,'userdata',ud);
plotfeatures(h0,1);

function plotfeatures(h0,op)

  % op = 1 => reset
  % op = 2 => draw selected points

disp('plotting features.');

 % get data to plot

ud = get(h0,'userdata');

 % now actually plot
titles={'1-2','1-3','1-4','2-3','2-4','3-4'};
axT   ={'ud.ax_1x2','ud.ax_1x3','ud.ax_1x4','ud.ax_2x3','ud.ax_2x4','ud.ax_3x4'};
X1    =[1 1 1 2 2 3];
Y1    =[2 3 4 3 4 4];

if ~isempty(ud.fea),
 for j=1:6,
  eval(['axes(' axT{j} ');']);
  if (op==1),
     hold off; op=1;
     plot(ud.fea(:,X1(j)),ud.fea(:,Y1(j)),'.',...
        'MarkerSize',1,'Color',[0.5 0.5 0.5],...
        'Tag','FeaAxes','userdata',[X1(j) Y1(j)]);
  end;
 end;
end;
%set(h0,'userdata',ud); right now, nothing changed so no reason to set

function plotspikes(h0,op)
NW = 15;
ud = get(h0,'userdata');

n = size(ud.spikes,2);
set(findobj(h0,'Tag','SpikeText'),'String',['Spikes (' int2str(n) ' total): ']);
numpages = ceil(n/NW);
sppage = ud.sppage;

if op==Inf,sppage=numpages; elseif op==-Inf, sppage=1;
else, sppage = sppage + op; end;
if sppage<1,sppage=1;elseif sppage>numpages,sppage=numpages;end;

if sppage==numpages,
  set(findobj(h0,'Tag','forend'),'enable','off');
  set(findobj(h0,'Tag','forward'),'enable','off');
else, 
  set(findobj(h0,'Tag','forend'),'enable','on');
  set(findobj(h0,'Tag','forward'),'enable','on');
end;
if sppage==1,
  set(findobj(h0,'Tag','backend'),'enable','off');
  set(findobj(h0,'Tag','backward'),'enable','off');
else, 
  set(findobj(h0,'Tag','backend'),'enable','on');
  set(findobj(h0,'Tag','backward'),'enable','on');
end;

sp_s = (sppage~=numpages)*((sppage-1)*15+1)+...
       (sppage==numpages)*((n>=15)*(n-14)+(n<15)*1);
sp_e = min([sp_s+14 n]);

cb = ['disp(mat2str(findobj(gcbf,''Tag'',''okbt'')));set(findobj(gcbf,''Tag'',''okbt''),''userdata'',gcbo);uiresume(gcbf);'];

for i=1:(sp_e-sp_s+1),
   set(ud.ax_sp(i),'Visible','on');
   axes(ud.ax_sp(i));
   plotcsp(ud.spikes(:,sp_s-1+i));
   L = size(ud.spikes,1)/4;
   set(gca,'xlim',[0 L+1],'xtick',[]);
   title(int2str(sp_s-1+i));
   aud = sp_s-1+i; %aud.sp = sp_s-1+i; aud.ax = i;
   set(gca,'Tag','SpikeAxes','userdata',aud,'ButtonDownFcn',cb);
   %set(gca,'Color',[0.9 0.9 0.9]+(1-ud.sel(sp_s-1+i))*[0.1 0.1 0.1]);
end;

 % turn off any unused displays
for i=(sp_e-sp_s+2):15, axes(ud.ax_sp(i)); cla; set(ud.ax_sp(i),'Visible','off'); end;

ud.sppage = sppage;
set(h0,'userdata',ud);

function updatefields(h0,theme)

params = getparameters(theme);
filtmethval = params.filtermethod + 1;
filtargstr = mat2str(params.filterarg);
threshstr = mat2str(params.thresh);
thresh2str = mat2str(params.thresh2);
thresh3str = mat2str(params.thresh3);
threshcovstr = mat2str(params.threshcov);
normalizeval = params.normalize + 1;
datadirval = params.datadir + 1;
oversamplingstr = num2str(params.oversampling);
pre_timestr = mat2str(params.pre_time);
post_timestr = mat2str(params.post_time);
remove_unresolvedval = params.remove_unresolved + 1;
peak_sepstr = mat2str(params.peak_sep);
overlap_sepstr = mat2str(params.overlap_sep);
event_sepstr = mat2str(params.event_sep);
scratchfilestr = params.scratchfile;
event_type_stringstr = params.event_type_string;
output_obj_val = params.output_object + 1;
useabsval = params.useabs + 1;

set(findobj(h0,'tag','thresh'),'String',threshstr);
set(findobj(h0,'tag','thresh2'),'String',thresh2str);
set(findobj(h0,'tag','thresh3'),'String',thresh3str);
set(findobj(h0,'tag','threshcov'),'String',threshcovstr);
set(findobj(h0,'tag','directionmenu'),'value',datadirval);
set(findobj(h0,'tag','filtertypemenu'),'value',filtmethval);
set(findobj(h0,'tag','filterarg'),'String',filtargstr);
set(findobj(h0,'tag','remove_unresolvedmenu'),'value',remove_unresolvedval);
set(findobj(h0,'tag','useabsmenu'),'value',useabsval);
set(findobj(h0,'tag','normalizemenu'),'value',normalizeval);
set(findobj(h0,'tag','oversampling'),'String',oversamplingstr);
set(findobj(h0,'tag','peak_sep'),'String',peak_sepstr);
set(findobj(h0,'tag','post_time'),'String',post_timestr);
set(findobj(h0,'tag','pre_time'),'String',pre_timestr);
set(findobj(h0,'tag','event_sep'),'String',event_sepstr);
set(findobj(h0,'tag','overlap_sep'),'String',overlap_sepstr);

function pstruct = checkinput(h0,p0);
ud = get(h0,'UserData');
so = 1; % syntax ok
try,t1=eval(get(findobj(h0,'Tag','thresh'),'String'));catch,errordlg('Syntax error in thresh.');so=0;end;
try,t2=eval(get(findobj(h0,'Tag','thresh2'),'String'));catch,errordlg('Syntax error in thresh2.');so=0;end;
try,t3=eval(get(findobj(h0,'Tag','thresh3'),'String'));catch,errordlg('Syntax error in thresh3.');so=0;end;
try,t4=eval(get(findobj(h0,'Tag','threshcov'),'String'));catch,errordlg('Syntax error in threshcov.');so=0;end;
try,fa=eval(get(findobj(h0,'Tag','filterarg'),'String'));catch,errordlg('Syntax error in filter arg.');so=0;end;
try,os=eval(get(findobj(h0,'Tag','oversampling'),'String'));catch,errordlg('Syntax error in oversampling.');so=0;end;
try,prt=eval(get(findobj(h0,'Tag','pre_time'),'String'));catch,errordlg('Syntax error in pre_time.');so=0;end;
try,pst=eval(get(findobj(h0,'Tag','post_time'),'String'));catch,errordlg('Syntax error in post_time.');so=0;end;
try,pk=eval(get(findobj(h0,'Tag','peak_sep'),'String'));catch,errordlg('Syntax error in peak_sep.');so=0;end;
try,ev=eval(get(findobj(h0,'Tag','event_sep'),'String'));catch,errordlg('Syntax error in event_sep.');so=0;end;
try,ol=eval(get(findobj(h0,'Tag','overlap_sep'),'String'));catch,errordlg('Syntax error in overlap_sep.');so=0;end;
if so,
        pstruct=struct('filtermethod',get(findobj(h0,'Tag','filtertypemenu'),'value')-1,...
                        'filterarg',fa,...
                        'thresh',t1,'thresh2',t2,...
                        'thresh3',t3,'threshcov',t4,...
                        'oversampling',os,'pre_time',prt,'post_time',pst,'peak_sep',pk,'event_sep',ev,...
                        'overlap_sep',ol,...
                        'useabs',get(findobj(h0,'Tag','useabsmenu'),'value')-1,...
                        'datadir',get(findobj(h0,'Tag','directionmenu'),'value')-1,...
                        'remove_unresolved',get(findobj(h0,'Tag','remove_unresolvedmenu'),'value')-1,...
                        'normalize',get(findobj(h0,'Tag','normalizemenu'),'value')-1,...
                        'scratchfile',p0.scratchfile,'event_type_string',p0.event_type_string,...
                        'output_object',p0.output_object);
        [good,err]=verifymultiextractor(pstruct);
        if ~good, errordlg(['Error in parameters: ' err]); pstruct = []; end;
else, pstruct = [];
end;


function h0 = buildwindow(theme,cksds)

cb = ['disp(mat2str(findobj(gcbf,''Tag'',''okbt'')));'...
      'set(findobj(gcbf,''Tag'',''okbt''),''userdata'',gcbo),uiresume(gcbf);'];

mat1 = [0 0 1;0 0.5 0;1 0 0;0 0.75 0.75;0.75 0 0.75;0.75 0.75 0;0.25 0.25 0.25];
h0 = figure('Color',[0.8 0.8 0.8], ...
        'PaperPosition',[18 180 576 432], ...
        'PaperUnits','points', ...
        'Position',[60 48 1228 895], ...
        'menubar','none');
		settoolbar('none');
ax_sp(15) = axes('Parent',h0, ...
        'Units','pixels', ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'NextPlot','add', ...
        'Position',[225 101 63 80], ...
        'Tag','SpikeAxes', ...
        'UserData',15, ...
        'XColor',[0 0 0], ...
        'XLim',[0 31], ...
        'XLimMode','manual', ...
        'XTickMode','manual', ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('15');
ax_sp(14) = axes('Parent',h0, ...
        'Units','pixels', ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'NextPlot','add', ...
        'Position',[137 101 63 80], ...
        'Tag','SpikeAxes', ...
        'UserData',14, ...
        'XColor',[0 0 0], ...
        'XLim',[0 31], ...
        'XLimMode','manual', ...
        'XTickMode','manual', ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('14');
ax_sp(13) = axes('Parent',h0, ...
        'Units','pixels', ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'NextPlot','add', ...
        'Position',[52 102 63 80], ...
        'Tag','SpikeAxes', ...
        'UserData',13, ...
        'XColor',[0 0 0], ...
        'XLim',[0 31], ...
        'XLimMode','manual', ...
        'XTickMode','manual', ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('13');
ax_sp(12) = axes('Parent',h0, ...
        'Units','pixels', ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'NextPlot','add', ...
        'Position',[225 200 63 80], ...
        'Tag','SpikeAxes', ...
        'UserData',12, ...
        'XColor',[0 0 0], ...
        'XLim',[0 31], ...
        'XLimMode','manual', ...
        'XTickMode','manual', ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('12');
ax_sp(11) = axes('Parent',h0, ...
        'Units','pixels', ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'NextPlot','add', ...
        'Position',[137 200 63 80], ...
        'Tag','SpikeAxes', ...
        'UserData',11, ...
        'XColor',[0 0 0], ...
        'XLim',[0 31], ...
        'XLimMode','manual', ...
        'XTickMode','manual', ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('11');
ax_sp(10) = axes('Parent',h0, ...
        'Units','pixels', ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'NextPlot','add', ...
        'Position',[52 201 63 80], ...
        'Tag','SpikeAxes', ...
        'UserData',10, ...
        'XColor',[0 0 0], ...
        'XLim',[0 31], ...
        'XLimMode','manual', ...
        'XTickMode','manual', ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('10');
ax_sp(9) = axes('Parent',h0, ...
        'Units','pixels', ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'NextPlot','add', ...
        'Position',[225 298 63 80], ...
        'Tag','SpikeAxes', ...
        'UserData',9, ...
        'XColor',[0 0 0], ...
        'XLim',[0 31], ...
        'XLimMode','manual', ...
        'XTickMode','manual', ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('9');
ax_sp(8) = axes('Parent',h0, ...
        'Units','pixels', ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'NextPlot','add', ...
        'Position',[137 298 63 80], ...
        'Tag','SpikeAxes', ...
        'UserData',8, ...
        'XColor',[0 0 0], ...
        'XLim',[0 31], ...
        'XLimMode','manual', ...
        'XTickMode','manual', ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('8');
ax_sp(7) = axes('Parent',h0, ...
        'Units','pixels', ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'NextPlot','add', ...
        'Position',[52 299 63 80], ...
        'Tag','SpikeAxes', ...
        'UserData',7, ...
        'XColor',[0 0 0], ...
        'XLim',[0 31], ...
        'XLimMode','manual', ...
        'XTickMode','manual', ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('7');
ax_sp(6) = axes('Parent',h0, ...
        'Units','pixels', ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'NextPlot','add', ...
        'Position',[225 397 63 80], ...
        'Tag','SpikeAxes', ...
        'UserData',6, ...
        'XColor',[0 0 0], ...
        'XLim',[0 31], ...
        'XLimMode','manual', ...
        'XTickMode','manual', ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('6');
ax_sp(5) = axes('Parent',h0, ...
        'Units','pixels', ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'NextPlot','add', ...
        'Position',[137 397 63 80], ...
        'Tag','SpikeAxes', ...
        'UserData',5, ...
        'XColor',[0 0 0], ...
        'XLim',[0 31], ...
        'XLimMode','manual', ...
        'XTickMode','manual', ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('5');
ax_sp(4) = axes('Parent',h0, ...
        'Units','pixels', ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'NextPlot','add', ...
        'Position',[52 398 63 80], ...
        'Tag','SpikeAxes', ...
        'UserData',4, ...
        'XColor',[0 0 0], ...
        'XLim',[0 31], ...
        'XLimMode','manual', ...
        'XTickMode','manual', ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('4');
ax_sp(3) = axes('Parent',h0, ...
        'Units','pixels', ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'NextPlot','add', ...
        'Position',[225 496 63 80], ...
        'Tag','SpikeAxes', ...
        'UserData',3, ...
        'XColor',[0 0 0], ...
        'XLim',[0 31], ...
        'XLimMode','manual', ...
        'XTickMode','manual', ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('3');
ax_sp(2) = axes('Parent',h0, ...
        'Units','pixels', ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'NextPlot','add', ...
        'Position',[137 496 63 80], ...
        'Tag','SpikeAxes', ...
        'UserData',2, ...
        'XColor',[0 0 0], ...
        'XLim',[0 31], ...
        'XLimMode','manual', ...
        'XTickMode','manual', ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('2');
ax_sp(1) = axes('Parent',h0, ...
        'Units','pixels', ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'NextPlot','add', ...
        'Position',[52 497 63 80], ...
        'Tag','SpikeAxes', ...
        'UserData',1, ...
        'XColor',[0 0 0], ...
        'XLim',[0 31], ...
        'XLimMode','manual', ...
        'XTickMode','manual', ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[169 52.00000000000001 124 42], ...
        'String','Spike Info:', ...
        'Style','text', ...
        'Tag','spinfo');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Max',4, ...
        'Min',1, ...
        'Position',[85 73 78.00000000000001 19], ...
        'String',{'zooms','shows data'}, ...
        'Style','popupmenu', ...
        'Tag','spclickmenu', ...
	'Callback',cb,...
        'Value',1);
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[38 71.00000000000001 47.00000000000001 19], ...
        'String','Clicking:', ...
        'Style','text', ...
        'Tag','StaticText5');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontSize',14, ...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[9 595 197 17], ...
        'String','Spikes: ', ...
        'Style','text', ...
        'Tag','SpikeText');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'Callback','', ...
        'ListboxTop',0, ...
        'Position',[84.00000000000001 31 40 19], ...
        'String','|<-', ...
	'Callback',cb,...
        'Tag','backend');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'Callback','', ...
        'ListboxTop',0, ...
        'Position',[129 31 40 19], ...
        'String','<-', ...
	'Callback',cb,...
        'Tag','backward');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'Callback','', ...
        'ListboxTop',0, ...
        'Position',[220 31 40 19], ...
        'String','->|', ...
	'Callback',cb,...
        'Tag','forend');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'Callback','', ...
        'ListboxTop',0, ...
        'Position',[174 31 40 19], ...
        'String','->', ...
	'Callback',cb,...
        'Tag','forward');
ax_3x4 = axes('Parent',h0, ...
        'Units','pixels', ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'NextPlot','add', ...
        'Position',[732 65 166 128], ...
        'Tag','FeaAxes', ...
        'UserData',[3 4], ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('3-4');
ax_2x4 = axes('Parent',h0, ...
        'Units','pixels', ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'NextPlot','add', ...
        'Position',[540 65 166 128], ...
        'Tag','FeaAxes', ...
        'UserData',[2 4], ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('2-4');
ax_2x3 = axes('Parent',h0, ...
        'Units','pixels', ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'NextPlot','add', ...
        'Position',[540 229 166 128], ...
        'Tag','FeaAxes', ...
        'UserData',[2 3], ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('2-3');
ax_1x4 = axes('Parent',h0, ...
        'Units','pixels', ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'NextPlot','add', ...
        'Position',[348 65 166 128], ...
        'Tag','FeaAxes', ...
        'UserData',[1 4], ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('1-4');
ax_1x3 = axes('Parent',h0, ...
        'Units','pixels', ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'NextPlot','add', ...
        'Position',[348 229 166 128], ...
        'Tag','FeaAxes', ...
        'UserData',[1 3], ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('1-3');
ax_1x2 = axes('Parent',h0, ...
        'Units','pixels', ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'NextPlot','add', ...
        'Position',[348 394 166 128], ...
        'Tag','FeaAxes', ...
        'UserData',[1 2], ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('1-2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[754 231 70.00000000000001 19], ...
        'String','overlap_sep:', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[814 232 90 21], ...
        'String','0.000501', ...
        'Style','edit', ...
	'Callback',cb,...
        'Tag','overlap_sep');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontWeight','bold', ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[939 125 230 15], ...
        'String','Spike waveform extraction parameters:', ...
        'Style','text', ...
        'Tag','StaticText4');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[1033 256 90 21], ...
        'String','0.0002', ...
        'Style','edit', ...
	'Callback',cb,...
        'Tag','event_sep');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[939 255 59.00000000000001 19], ...
        'String','event_sep:', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[939 79.00000000000001 59.00000000000001 19], ...
        'String','Post-time:', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[1003 80.00000000000001 120 21], ...
        'String','0.0006', ...
        'Style','edit', ...
	'Callback',cb,...
        'Tag','post_time');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[815 254 90 21], ...
        'String','9e-05', ...
        'Style','edit', ...
	'Callback',cb,...
        'Tag','peak_sep');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[752 253 64 19], ...
        'String','peak_sep:', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontWeight','bold', ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[754 376.0000000000001 117 15], ...
        'String','Detection parameters:', ...
        'Style','text', ...
        'Tag','StaticText4');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[1003 282 120 21], ...
        'String','18.4668269529032', ...
	'Callback',cb,...
        'Style','edit', ...
        'Tag','threshcov');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[751 284 239 16], ...
        'String','Threshcov (ID''s spiking vs. non-spiking):', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[939 59 103 17], ...
        'String','Oversampling:', ...
        'Style','text', ...
        'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[1054 60.00000000000001 69 19], ...
        'String','1', ...
        'Style','edit', ...
	'Callback',cb,...
        'Tag','oversampling');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Max',3, ...
        'Min',1, ...
        'Position',[1033 229 90 19], ...
        'String',{'none','std dev','cov'}, ...
        'Style','popupmenu', ...
        'Tag','normalizemenu', ...
        'UserData','[ ]', ...
	'Callback',cb,...
        'Value',3);
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[939 229 64 17], ...
        'String','Normalizing:', ...
        'Style','text', ...
        'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Max',2, ...
        'Min',1, ...
        'Position',[1033 172 90 19], ...
        'String',{'no','yes'}, ...
        'Style','popupmenu', ...
	'Callback',cb,...
        'Tag','useabsmenu', ...
        'Value',1);
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[939 170 75 17], ...
        'String','Use abs value:', ...
        'Style','text', ...
        'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Max',2, ...
        'Min',1, ...
        'Position',[1054 147 69 19], ...
        'String',{'no','yes'}, ...
        'Style','popupmenu', ...
        'Tag','remove_unresolvedmenu', ...
	'Callback',cb,...
        'Value',2);
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[939 146 103 17], ...
        'String','Remove unresolved?', ...
        'Style','text', ...
        'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[754 307.0000000000001 192 16], ...
        'String','Thresh3 (unresolvable spike thresh):', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[939 99 55.00000000000001 19], ...
        'String','Pre-time:', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[1003 306 120 21], ...
        'String','33.376841581676', ...
        'Style','edit', ...
	'Callback',cb,...
        'Tag','thresh3');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[1003 101 120 21], ...
        'String','0.0003', ...
        'Style','edit', ...
	'Callback',cb,...
        'Tag','pre_time');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Max',2, ...
        'Position',[992.9999999999999 397.0000000000001 130 19], ...
        'String','[0.0190851835358483 0.636172784528278]', ...
        'Style','edit', ...
	'Callback',cb,...
        'Tag','filterarg');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[939 398.0000000000001 42 17], ...
        'String','Arg:', ...
        'Style','text', ...
        'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[754 398.0000000000001 76 17], ...
        'String','Filter method:', ...
        'Style','text', ...
        'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Max',3, ...
        'Min',1, ...
        'Position',[833 398 89 19], ...
        'String',{'none','convolution','Chebyshev I'}, ...
        'Style','popupmenu', ...
        'Tag','filtertypemenu', ...
	'Callback',cb,...
        'Value',3);
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[44 738 67 22], ...
        'String','Help', ...
	'Callback',cb,...
        'Tag','HelpBt');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'Callback',cb,...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[44 763 67 22], ...
        'String','Cancel', ...
        'Tag','Cancelbt', ...
	'Callback',cb,...
        'UserData',0);
okbt = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'Callback',cb,...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[44 786 67 22], ...
        'String','OK', ...
        'Tag','okbt', ...
	'Callback',cb,...
        'UserData',0);
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[939 201 64 17], ...
        'String','Direction:', ...
        'Style','text', ...
        'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Max',3, ...
        'Min',1, ...
        'Position',[1033 201 90 19], ...
        'String',{'0','-','+'}, ...
        'Style','popupmenu', ...
        'Tag','directionmenu', ...
	'Callback',cb,...
        'Value',2);
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[1003 329 120 21], ...
        'String','38.2396001180392', ...
        'Style','edit', ...
	'Callback',cb,...
        'Tag','thresh2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[1003 353 120 21], ...
        'String','200', ...
	'Callback',cb,...
        'Style','edit', ...
        'Tag','thresh');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[754 332 176 14], ...
        'String','Thresh2 (secondary peak threshold):', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[754 354 178 16], ...
        'String','Thresh1 (peak detection threshold):', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontSize',12, ...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[756 420 185 19], ...
        'String','Multiextractor editor:', ...
        'Style','text', ...
        'Tag','StaticText1');
zoom_raw = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'Position',[318 700 262 139], ...
        'Tag','zoom_raw', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('zoom raw');
h1 = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'Position',[318 561 262 139], ...
        'Tag','zoom_energy', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('zoom energy');
h1 = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'Position',[619 700 565 139], ...
        'Tag','full_raw', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('full_raw');
h1 = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat1, ...
        'Position',[619 561 565 139], ...
        'Tag','full_energy', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
title('full energy');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[393 844 116 17], ...
        'String','Close-up', ...
        'Style','text', ...
        'Tag','StaticText6');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[850 844 116 17], ...
        'String','Far out', ...
        'Style','text', ...
        'Tag','StaticText6');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontSize',14, ...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[49 831 225 26], ...
        'String','Multiextractor data browser', ...
        'Style','text', ...
        'Tag','StaticText7');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[202 657 73 15], ...
        'String','energy', ...
        'Style','text', ...
        'Tag','StaticText8');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[202 632 73 15], ...
        'String','neg energy', ...
        'Style','text', ...
        'Tag','StaticText8');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[202 609 73 15], ...
        'String','pos energy', ...
        'Style','text', ...
        'Tag','StaticText8');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[44 710 67 22], ...
	'Callback',cb,...
        'String','Open data...', ...
        'Tag','OpenDataBt');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontSize',12, ...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[535 472 118 19], ...
        'String','Clustergrams:', ...
        'Style','text', ...
        'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'ListboxTop',0, ...
        'Position',[1132 355.0000000000001 32 18], ...
        'String','Set', ...
	'Callback',cb,...
        'Tag','threshbt');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'ListboxTop',0, ...
        'Position',[1132 330 32 18], ...
        'String','Set', ...
	'Callback',cb,...
        'Tag','thresh2bt');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'ListboxTop',0, ...
        'Position',[1132 307.0000000000001 32 18], ...
        'String','Set', ...
	'Callback',cb,...
        'Tag','thresh3bt');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'ListboxTop',0, ...
        'Position',[1132 284 32 18], ...
        'String','Set', ...
	'Callback',cb,...
        'Tag','threshcovbt');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'ListboxTop',0, ...
        'Position',[1132 259 32 18], ...
        'String','Set', ...
	'Callback',cb,...
        'Tag','eventtimebt');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'ListboxTop',0, ...
        'Position',[905 233 32 18], ...
        'String','Set', ...
	'Callback',cb,...
        'Tag','peak_sepbt');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'ListboxTop',0, ...
        'Position',[905 258 32 18], ...
        'String','Set', ...
	'Callback',cb,...
        'Tag','overlapbt');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'ListboxTop',0, ...
        'Position',[1132 59 32 18], ...
        'String','Set', ...
	'Callback',cb,...
        'Tag','pretimebt');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'ListboxTop',0, ...
        'Position',[1132 84 32 18], ...
        'String','Set', ...
	'Callback',cb,...
        'Tag','posttimebt');
featuremenu = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Min',1, ...
        'Position',[500 400 97.01740895669292 20.17193651574803], ...
        'String',{'Peaks','V at Max E'}, ...
        'Style','popupmenu', ...
        'Tag','featuremenu', ...
        'Value',1,'Callback',cb);

data.data = [];
data.interval = [];
set(h0,'userdata',struct('ax_sp',ax_sp,'ax_1x2',ax_1x2,'ax_1x3',...
        ax_1x3,'ax_1x4',ax_1x4,'ax_2x3',ax_2x3,'ax_2x4',ax_2x4,...
          'ax_3x4',ax_3x4,'okbt',okbt,'spikes',[],'stime',[],...
           'spikeloc',1,'sppage',1,'fea',[],'cksds',cksds,...
           'theme',theme,'data',data,'cest',[],'idx',[],'stype',[],...
           'currspike',[],'ttime',[],'thecov',[]));
          
