pwd = which('NelsonLabToolsInit');

pi = find(pwd==filesep); 
pwd = [pwd(1:pi(end)-1) filesep];

addpath(pwd,...   % fullfile(pwd, 'GeneticRFMapper'),...
    fullfile(pwd, 'data_extraction'),...
    fullfile(pwd, 'ExperimentPanels'),...
    fullfile(pwd, 'ExperimentPanels' , 'usefulcalls'),...
    fullfile(pwd, 'ExperimentPanels','panelcallbacks'),...    
    fullfile(pwd, 'data_extraction' , 'tempfuncs'),...
    fullfile(pwd, 'data_extraction' , 'spike2cell'),...
    fullfile(pwd, 'Analysis'),... 
    fullfile(pwd, 'Analysis' , 'lgnanalysis'),...
    fullfile(pwd, 'Analysis' , 'lgnctxanalysis'),...
    fullfile(pwd, 'Analysis' , 'lgnctxcsdanalysis'),...
    fullfile(pwd, 'Analysis' , 'ctxanalysis'),... %    fullfile(pwd, 'Analysis' , 'mlanalysis'),...
    fullfile(pwd, 'Analysis' , 'general'));

windowdiscriminator('default');
cksmultipleunit([1 2],'','',1.5,[]);
wdcluster('default');
multiextractor('default');
dotdiscriminator('default');

%NelsonLabToolsInitLocal;

clear('pi','pwd');
