pwd = which('NelsonLabToolsInit');

pi = find(pwd==filesep); 
pwd = [pwd(1:pi(end)-1) filesep];

addpath(pwd,...   % fullfile(pwd, 'GeneticRFMapper'),...
    fullfile(pwd, 'ExperimentPanels'),...
    % fullfile(pwd, 'ExperimentPanels' , 'usefulcalls'),...
    % fullfile(pwd, 'ExperimentPanels','panelcallbacks'),...    
    fullfile(pwd, 'Analysis'),... 
    fullfile(pwd, 'Analysis' , 'lgnanalysis'),...
    fullfile(pwd, 'Analysis' , 'lgnctxanalysis'),...
    fullfile(pwd, 'Analysis' , 'lgnctxcsdanalysis'),...
    fullfile(pwd, 'Analysis' , 'ctxanalysis'),... %    fullfile(pwd, 'Analysis' , 'mlanalysis'),...
    fullfile(pwd, 'Analysis' , 'general'));


%NelsonLabToolsInitLocal;

clear('pi','pwd');
