function graph_clust(thewdc,L,outname,ds)

%L = load(fname,'-mat');


h0 = buildwindow;
ud = get(h0,'userdata');
  % initialize
n = size(L.csp,2); ud.sel = zeros(n,1); ud.cl  = zeros(n,1); ud.cellcl = {[]};
ud.sppage = 1; ud.feaplot_uncl = -1*ones(6,1); ud.feaplot_sel = -1*ones(6,1);
ud.feaplot_curcl = {-1 -1 -1 -1 -1 -1};
set(h0,'userdata',ud);
if ~isempty(ds),
   disp('Restoring from ds.');
   ud.cellcl = ds.cellcl;
   ud.cellclstr = ds.cellclstr;
   set(findobj(h0,'Tag','lb'),'String',ds.cellclstr);
   set(findobj(h0,'Tag','featuremenu'),'value',ds.feature);
   set(findobj(h0,'Tag','redisplay'),'value',ds.redisplay);
   set(h0,'userdata',ud);
   setfeatures(h0,L);
   drawclustlb(h0); dodrawcluster(h0,L);
else,
   setfeatures(h0,L);
end;

plotspikes(h0,L.csp,0);
ud = get(h0,'userdata');
plotfeatures(h0,1);
plotselectedspikes(h0,L.csp);

zoom on;
done = 0;
while ~done,
  uiwait(h0);
  o = get(findobj(h0,'Tag','okbt'),'userdata');
  ud = get(h0,'userdata');
  if strcmp(get(o,'Tag'),'Axes'),

  else,
     name = get(o,'Tag'); disp(name);
         if strcmp(name,'forward'),  plotspikes(h0,L.csp,1);
     elseif strcmp(name,'forend'),   plotspikes(h0,L.csp,Inf);
     elseif strcmp(name,'backward'), plotspikes(h0,L.csp,-1);
     elseif strcmp(name,'backend'),  plotspikes(h0,L.csp,-Inf);
     elseif strcmp(name,'spclickmenu'),
         switch get(o,'value'),
            case 1, % zoom
               zoom on;
               set(findobj(h0,'Tag','feaclickmenu'),'value',1);
            case {2,3,4},
               zoom off;
               if get(findobj(h0,'Tag','feaclickmenu'),'value')==1,
                  set(findobj(h0,'Tag','feaclickmenu'),'value',2);
               end;
         end;
     elseif strcmp(name,'feaclickmenu'),
         switch get(o,'value'),
            case 1, % zoom,
               zoom on;
               set(findobj(h0,'Tag','spclickmenu'),'value',1);
            case 2,
               zoom off;
               if get(findobj(h0,'Tag','spclickmenu'),'value')==1,
                  set(findobj(h0,'Tag','spclickmenu'),'value',2);
               end;
          end;
          dosetfeaclick(h0,o,findobj(h0,'Tag','feaselectmenu'));
     elseif strcmp(name,'featuremenu'),
	setfeatures(h0,L); plotfeatures(h0,1); plotselectedspikes(h0,L.csp);
     elseif strcmp(name,'ms_uncl')|strcmp(name,'sym_uncl'),
        plotfeatures(h0,1);
     elseif strcmp(name,'ms_sel')|strcmp(name,'sym_sel'),
        plotfeatures(h0,2);
     elseif strcmp(name,'ms_ccl')|strcmp(name,'sym_ccl')|strcmp(name,'ms_cl')|strcmp(name,'sym_cl'),
        plotfeatures(h0,4);
     elseif strcmp(name,'feaselectmenu'),
        dosetfeaclick(h0,findobj(h0,'Tag','feaclickmenu'),o);
     elseif strcmp(name,'deselect')|strcmp(name,'deselectfea'),
         ud.sel = zeros(n,1); ud.selcl = []; set(h0,'userdata',ud);
         plotspikes(h0,L.csp,0); plotfeatures(h0,2); plotselectedspikes(h0,L.csp);
     elseif strcmp(name,'selectedtext'),
         disp(['handling']);
         if isnumeric(get(o,'userdata')),gotopage(h0,get(o,'userdata'),L.csp);end;
     elseif strcmp(name,'selectedplots'),
         ch = get(get(o,'Parent'),'children');
         selinds = find(ud.sel); selinds=selinds(end:-1:1);
         ind = find(ch==o);
         set(findobj(h0,'Tag','selectedtext'),'String',['spike is # ' int2str(selinds(ind)) '.'],'userdata',selinds(ind));
     elseif strcmp(name,'SpikeAxes'),
         switch get(findobj(h0,'Tag','spclickmenu'),'value'),
            case 1, % zoom, we should not see this case
            case 2, % select
               aud = get(o,'userdata');
               ud.sel(aud.sp) = 1-ud.sel(aud.sp);
               set(h0,'userdata',ud);
               plotspikes(h0,L.csp,0);
               plotfeatures(h0,2); plotselectedspikes(h0,L.csp);
               set(findobj(h0,'tag','spinfo'),'String',...
                {['Spike # ' int2str(aud.sp) ', ' sprintf('%0.4fs',L.stmp(aud.sp))],...
                 ['samp # ' int2str(L.stime(aud.sp)) ', cluster: ' int2str(ud.cl(aud.sp)) ]});
            case 3,
               aud = get(o,'userdata');
               set(findobj(h0,'tag','spinfo'),'String',...
                {['Spike # ' int2str(aud.sp) ', ' sprintf('%0.4fs',L.stmp(aud.sp))],...
                 ['samp # ' int2str(L.stime(aud.sp)) ', cluster: ' int2str(ud.cl(aud.sp)) ]});
            case 4, % not yet IMP
         end;
      elseif strcmp(name,'FeaAxes'),
         disp('FeaAxes handler');
         o2 = o+(strcmp(get(o,'Type'),'axes')-1)*(+o-get(o,'parent'));
         switch get(findobj(h0,'Tag','feaselectmenu'),'value')
            case 1,  c0=get(o2,'CurrentPoint');c0=c0([1 3]);
                     hold on;
                     tmpplot = plot(c0(1),c0(2),'*','Color',[1 0.0 0.8]);
                     [xr,yr]=ginput(1);
                     delete(tmpplot);
                     r = pdist([c0 ; xr yr],'euclid');
                     shape = struct('center',c0,'radius',r,'chans',get(o2,'userdata'));
                     options = struct('burst',0,'garbage',0);
                     ud.selcl = [struct('type','circle','op','|','params',shape,'options',options)];
                     set(h0,'userdata',ud);
                     plotfeatures(h0,2); plotspikes(h0,L.csp,0); plotselectedspikes(h0,L.csp);
                     ud = get(h0,'userdata'); ud.selcl = []; set(h0,'userdata',ud);
            case 2000,  c0=get(o2,'CurrentPoint');c0=c0([1 3]); % not used anymore
                     hold on;
                     tmpplot0 = plot(c0(1),c0(2),'*','Color',[1 0.0 0.8]);
                     [x1,y1]=ginput(1);
                     tmpplot1=plot([c0(1) x1],[c0(2) y1],'color',[1 0.0 0.8],'linewidth',2);
                     [x2,y2]=ginput(1);
                     
                     delete(tmpplot0); delete(tmpplot1);
                     shape = struct('center',c0,'axes',[x1 y1; x2 y2],'chans',get(o2,'userdata'));
                     options = struct('burst',0,'garbage',0);
                     ud.selcl = [struct('type','elipse','params',shape,'op','|','options',options)];
                     set(h0,'userdata',ud);
                     plotfeatures(h0,2); plotspikes(h0,L.csp,0); plotselectedspikes(h0,L.csp);
                     ud = get(h0,'userdata'); ud.selcl = []; set(h0,'userdata',ud);
            case 3,
         end;
      elseif strcmp(name,'newclprop'),
         if ~isempty(get(findobj(h0,'Tag','lb'),'String')),
           cli = get(findobj(h0,'Tag','lb'),'value');
           str = {'Add selected spikes','Add elipse'};
           [s,v]=listdlg('PromptString','Add property:','SelectionMode','single','ListString',str);
           if ~isempty(s),
            switch s,
              case 0, % cancelled
              case 1, 
               inds = find(ud.sel);
               params = struct('inds',inds,'times',L.stime(inds));
               newprop = struct('type','selected','params',params,'op','|','options',getclops(h0));
               prname = 'selected';
               str = get(findobj(h0,'Tag','clustlb'),'String');
               str = cat(1,{'selected'},str);
              case 2,
               inds = find(ud.sel);
               c = cov(ud.fea(inds,:)); m = mean(ud.fea(inds,:));
               params = struct('sqspan',c,'center',m,'chans',[1 2 3 4],'drawmult',2,'mult',2);
               newprop = struct('type','elipse','params',params,'op','|','options',getclops(h0));
               prname = 'elipse';
            end;
           end;
           if exist('newprop'),
              ud.cellcl{cli} = [newprop ud.cellcl{cli}];
               str = get(findobj(h0,'Tag','clustlb'),'String');
               str = cat(1,{prname},str);
               set(findobj(h0,'Tag','clustlb'),'String',str);
               set(h0,'userdata',ud);
               dodrawcluster(h0,L);
           end;
         end;
      elseif strcmp(name,'deleteclprop'),
         if ~isempty(get(findobj(h0,'Tag','lb'),'String')),
           cli = get(findobj(h0,'Tag','lb'),'value');
           v = get(findobj(h0,'Tag','clustlb'),'value');
           ud.cellcl{cli} = ud.cellcl{cli}([1:(v-1) (v+1):length(ud.cellcl{cli})]);
           str = get(findobj(h0,'Tag','clustlb'),'String');
           str = {str{[1:(v-1) (v+1):length(str)]}};
           set(findobj(h0,'Tag','clustlb'),'String',str);
           set(h0,'userdata',ud);
           dodrawcluster(h0,L);
         end;
      elseif strcmp(name,'editclprop'),
         if ~isempty(get(findobj(h0,'Tag','lb'),'String')),
           cli = get(findobj(h0,'Tag','lb'),'value');
           v = get(findobj(h0,'Tag','clustlb'),'value');
           g = editclprop(ud.cellcl{cli}(v),h0,L);
           if ~isempty(g), ud.cellcl{cli}(v) = g; end;
           set(h0,'userdata',ud);
           dodrawcluster(h0,L);
         end;
      elseif strcmp(name,'selcluster'),
         if ~isempty(get(findobj(h0,'Tag','lb'),'String')),
           cli = get(findobj(h0,'Tag','lb'),'value');
           ud.sel = wdc_findptsincluster(ud.fea,ud.cellcl{cli});
           set(h0,'userdata',ud);
           plotspikes(h0,L.csp,0); plotfeatures(h0,2); plotselectedspikes(h0,L.csp);
         end;
      elseif strcmp(name,'garbage')|strcmp(name,'burster'),
         setops(h0);
      elseif strcmp(name,'newbt'),
         ud.cellcl = cat(1,{[]},ud.cellcl);
         str = get(findobj(h0,'Tag','lb'),'String');
         l = length(str);
         str = cat(1,{['clust' int2str(l+1)]},str);
         set(findobj(h0,'Tag','lb'),'String',str);
         ud.cellclstr = str;
         set(h0,'userdata',ud);
         drawclustlb(h0); dodrawcluster(h0,L);
      elseif strcmp(name,'deletebt'),
         str = get(findobj(h0,'Tag','lb'),'String');
         v = get(findobj(h0,'Tag','lb'),'value');
         ud.cellcl = {ud.cellcl{[1:(v-1) (v+1):length(ud.cellcl)]}},
         str = {str{[1:(v-1) (v+1):length(str)]}};
         set(findobj(h0,'Tag','lb'),'String',str);
         ud.cellclstr = str;
         set(h0,'userdata',ud);
         drawclustlb(h0); dodrawcluster(h0,L);
      elseif strcmp(name,'lb'),
         drawclustlb(h0); dodrawcluster(h0,L);
      elseif strcmp(name,'okbt'),
         ds = struct('feature',get(findobj(h0,'Tag','featuremenu'),'value'),...
                     'cellcl',{ud.cellcl},'cellclstr',{ud.cellclstr},...
                     'redisplay',get(findobj(h0,'Tag','redisplay'),'value'),...
                     'stime',L.stime,'wdc',thewdc);
         ds,
         save(outname,'ds','-mat'); % no error checking
         done = 1;
      end;
  end;
end;

delete(h0);

function setops(h0) % sets ud
ud = get(h0,'userdata');
cli = get(findobj(h0,'Tag','lb'),'value');
if ~isempty(cli),
  if ~isempty(ud.cellcl{cli}),
    ud.cellcl{cli}(1).options = getclops(h0);
  end;
end;
set(h0,'userdata',ud);

function drawclustlb(h0)
ud = get(h0,'userdata');
str = {}; v = [];
if ~isempty(get(findobj(h0,'Tag','lb'),'String')),
  cli = get(findobj(h0,'Tag','lb'),'value');
  if ~isempty(cli),
    if ~isempty(ud.cellcl{cli}),
      ops = ud.cellcl{cli}(1).options;
      set(findobj(h0,'Tag','burster'),'value',ops.burst); set(findobj(h0,'Tag','garbage'),'value',ops.garbage);
    else,
      set(findobj(h0,'Tag','burster'),'value',0); set(findobj(h0,'Tag','garbage'),'value',0);
    end; 
    for i=1:length(ud.cellcl{cli}),
      v = 1; str{i} = ud.cellcl{cli}(i).type;
    end;
  end;
end;
set(findobj(h0,'Tag','clustlb'),'String',str,'value',1);


function ops = getclops(h0)
ops = struct('burst',get(findobj(h0,'Tag','burster'),'value'),'garbage',get(findobj(h0,'Tag','garbage'),'value'));

function g = editclprop(prop,h0,L)
g = [];
ud = get(h0,'userdata');
    if strcmp(prop.type,'selected'),
  inds = 1:length(ud.sel);
  prompt = {'indicies'};
  def = {mat2str(prop.params.inds)};
  dlgTitle = 'Modify type ''selected''';
  lineNo = 10;
  answer = inputdlg(prompt,dlgTitle,lineNo,def);
  if isempty(answer), g = []; return;
  else,
    try,
        eval(['inds2 = ' answer{1} ';']);
        inds2 = intersect(inds,inds2);
        g = prop;
        g.params = struct('inds',inds2,'times',L.stime(inds2));
    catch, g = []; errordlg('Could not change type selected.'); return;
    end;
  end;
elseif strcmp(prop.type,'circle'),
elseif strcmp(prop.type,'elipse'),
end;

function plotselectedspikes(h0,spikes)
 % no need to save states, just plot
 cb = ['disp(mat2str(findobj(gcbf,''Tag'',''okbt'')));set(findobj(gcbf,''Tag'',''okbt''),''userdata'',gcbo);uiresume(gcbf);'];
 getselected(h0);
 ud=get(h0,'userdata');
 l = size(spikes,1)/4;
 inds = find(ud.sel==1);
 cs = [(1:l);(l+1:2*l);(2*l+1):(3*l);(3*l+1):(4*l)];cs(1,end),cs(2,end),cs(3,end),cs(4,end),
 axes(ud.ax_sel(1)); cla;
 if ~isempty(inds), plot(spikes(cs(1,:),inds),'Tag','selectedplots','userdata',1,'ButtonDownFcn',cb); end;
 set(gca,'xlim',[0 cs(1,end)+1],'xtick',[]); a1 = axis;
 axes(ud.ax_sel(2)); cla;
 if ~isempty(inds), plot(spikes(cs(2,:),inds),'Tag','selectedplots','userdata',2,'ButtonDownFcn',cb); end;
 set(gca,'xlim',[0 cs(1,end)+1],'xtick',[]); a2 = axis;
 axes(ud.ax_sel(3)); cla;
 if ~isempty(inds), plot(spikes(cs(3,:),inds),'Tag','selectedplots','userdata',3,'ButtonDownFcn',cb); end;
 set(gca,'xlim',[0 cs(1,end)+1],'xtick',[]); a3 = axis;
 axes(ud.ax_sel(4)); cla;
 if ~isempty(inds), plot(spikes(cs(4,:),inds),'Tag','selectedplots','userdata',4,'ButtonDownFcn',cb); end;
 set(gca,'xlim',[0 cs(1,end)+1],'xtick',[]); a4 = axis;
 ylim= [min([a1(3) a2(3) a3(3) a4(3)]) max([a1(4) a2(4) a3(4) a4(4)])],
 set(ud.ax_sel(1),'ylim',ylim); set(ud.ax_sel(2),'ylim',ylim,'YAxisLocation','right');
 set(ud.ax_sel(3),'ylim',ylim); set(ud.ax_sel(4),'ylim',ylim,'YAxisLocation','right');


function dodrawcluster(h0,L)
ud=get(h0,'userdata');
if ~isempty(get(findobj(h0,'Tag','lb'),'String')),
 cli = get(findobj(h0,'Tag','lb'),'value');
 inds = find(wdc_findptsincluster(ud.fea,ud.cellcl{cli}));
 % no need to save states, just plot
 cb = ['disp(mat2str(findobj(gcbf,''Tag'',''okbt'')));set(findobj(gcbf,''Tag'',''okbt''),''userdata'',gcbo);uiresume(gcbf);'];
 l = size(L.csp,1)/4;
 cs = [(1:l);(l+1:2*l);(2*l+1):(3*l);(3*l+1):(4*l)];
 disp(['Found ' length(inds) '.']);
 axes(ud.ax_cl(1)); cla;
 if ~isempty(inds), plot(L.csp(cs(1,:),inds),'Tag','clusterplots','userdata',1,'ButtonDownFcn',cb); end;
 set(gca,'xlim',[0 cs(1,end)+1],'xtick',[]); a1 = axis;
 axes(ud.ax_cl(2)); cla;
 if ~isempty(inds), plot(L.csp(cs(2,:),inds),'Tag','clusterplots','userdata',2,'ButtonDownFcn',cb); end;
 set(gca,'xlim',[0 cs(1,end)+1],'xtick',[]); a2 = axis;
 axes(ud.ax_cl(3)); cla;
 if ~isempty(inds), plot(L.csp(cs(3,:),inds),'Tag','clusterplots','userdata',3,'ButtonDownFcn',cb); end;
 set(gca,'xlim',[0 cs(1,end)+1],'xtick',[]); a3 = axis;
 axes(ud.ax_cl(4)); cla;
 if ~isempty(inds), plot(L.csp(cs(4,:),inds),'Tag','clusterplots','userdata',4,'ButtonDownFcn',cb); end;
 set(gca,'xlim',[0 cs(1,end)+1],'xtick',[]); a4 = axis;
 ylim= [min([a1(3) a2(3) a3(3) a4(3)]) max([a1(4) a2(4) a3(4) a4(4)])],
 set(ud.ax_cl(1),'ylim',ylim); set(ud.ax_cl(2),'ylim',ylim,'YAxisLocation','right');
 set(ud.ax_cl(3),'ylim',ylim); set(ud.ax_cl(4),'ylim',ylim,'YAxisLocation','right');
 plotfeatures(h0,4);
end;

function dosetfeaclick(h0,feamenu,feaselmenu)
if get(feamenu,'value')==2,
  switch get(feaselmenu,'value'),
     case 1, set(findobj(h0,'Tag','selecthelptext'), ...
        'String','click center then point on radius');
     case 2, set(findobj(h0,'Tag','selecthelptext'), ...
        'String',{'click center then point on one','axis then point on other axis'});
     case 3, set(findobj(h0,'Tag','selecthelptext'), ...
        'String',{'click sequence of points,', 'then hit return to complete'});
  end;
else, set(findobj(h0,'Tag','selecthelptext'),'String','');
end;

function setfeatures(h0,L)  % sets userdata
ud = get(h0,'userdata');
switch get(findobj(h0,'Tag','featuremenu'),'value'),
   case 1, % peaks
      ud.fea = wdc_extractPeaks(L.csp,L.spikeloc,1); % need to get data dir IMP
   case 2, % values at max energy
      ud.fea = wdc_extractRaw(L.csp,L.spikeloc)';
end;
set(h0,'userdata',ud);

function getselected(h0) % modifies userdata
  ud = get(h0,'userdata');
  inds = wdc_findptsincluster(ud.fea,ud.selcl);
  ud.sel(find(inds))=1;
  set(h0,'userdata',ud);

function plotfeatures(h0,op)

  % op = 1 => reset
  % op = 2 => draw selected points

disp('plotting features.');
cb = ['disp(mat2str(findobj(gcbf,''Tag'',''okbt'')));set(findobj(gcbf,''Tag'',''okbt''),''userdata'',gcbo);uiresume(gcbf);'];

ud = get(h0,'userdata');
msv = get(findobj(h0,'Tag','ms_uncl'),'value'); mss = get(findobj(h0,'Tag','ms_uncl'),'String');
syv = get(findobj(h0,'Tag','sym_uncl'),'value'); sys = get(findobj(h0,'Tag','sym_uncl'),'String');
msuncl = str2num(mss{msv}); symuncl = sys{syv};
msv = get(findobj(h0,'Tag','ms_sel'),'value'); mss = get(findobj(h0,'Tag','ms_sel'),'String');
syv = get(findobj(h0,'Tag','sym_sel'),'value'); sys = get(findobj(h0,'Tag','sym_sel'),'String');
mssel = str2num(mss{msv}); symsel = sys{syv};
msv = get(findobj(h0,'Tag','ms_cl'),'value'); mss = get(findobj(h0,'Tag','ms_cl'),'String');
syv = get(findobj(h0,'Tag','sym_cl'),'value'); sys = get(findobj(h0,'Tag','sym_cl'),'String');
mscl = str2num(mss{msv}); symcl = sys{syv};
msv = get(findobj(h0,'Tag','ms_ccl'),'value'); mss = get(findobj(h0,'Tag','ms_ccl'),'String');
syv = get(findobj(h0,'Tag','sym_ccl'),'value'); sys = get(findobj(h0,'Tag','sym_ccl'),'String');
mscrcl = str2num(mss{msv}); symcrcl = sys{syv};

axes(ud.ax_key);
hold off; plot(0,4,symuncl,'color',[0.5 0.5 0.5],'MarkerSize',msuncl);
hold on; plot(0,3,symsel,'color', [0.0 1.0 0.0],'MarkerSize',mssel);
plot(0,2,symcl,'color',[1 0.0 0.0],'MarkerSize',mscl);
plot(0,1,symcrcl,'color',[0 0 0],'MarkerSize',mscrcl);
set(gca,'xtick',[],'ytick',[],'ylim',[0 5]);

 % get data to plot

if (op==2)|(op==1)|(op==4),
  getselected(h0); ud = get(h0,'userdata');
  set(findobj(h0,'Tag','numptssel'),'String',int2str(length(find(ud.sel))));
end;
self = find(ud.sel);

plotstr = ''; inc = 1;
v = get(findobj(h0,'Tag','lb'),'value');
if (op==4)|(op==1),
  clinds = wdc_clusterall(ud.cellcl,ud.fea);
  for j=1:size(clinds,2);
    if (~isempty(v))&(v==j), currinds = find(wdc_findptsincluster(ud.fea,ud.cellcl{v})); end;
    z = find(clinds(:,j));
    %if length(z)~=0,
       X{inc} = z;
       %plotstr=[plotstr 'ud.fea(X{' int2str(inc) '},X1(j)),ud.fea(X{' int2str(inc) '},Y1(j)),'];
       inc = inc + 1;
    %end;
  end;
end;
inc = inc-1;
if length(plotstr)~=0, plotstr = plotstr(1:end-1); end; % remove trailing comma
if op==2,currinds=1;end; % so won't get erased

 % now actually plot
titles={'1-2','1-3','1-4','2-3','2-4','3-4'};
axT   ={'ud.ax_1x2','ud.ax_1x3','ud.ax_1x4','ud.ax_2x3','ud.ax_2x4','ud.ax_3x4'};
X1    =[1 1 1 2 2 3];
Y1    =[2 3 4 3 4 4];

for j=1:6,
  eval(['axes(' axT{j} ');']);
  if ~ishandle(ud.feaplot_uncl(j))|(op==1),
     hold off; op=1;
     ud.feaplot_uncl(j) = plot(ud.fea(:,X1(j)),ud.fea(:,Y1(j)),symuncl,'MarkerSize',msuncl,'Color',[0.5 0.5 0.5],...
        'Tag','FeaAxes','userdata',[X1(j) Y1(j)],'ButtonDownFcn',cb);
  end;
  if ishandle(ud.feaplot_curcl{j}(end))&((length(currinds)==0)|(op==4)),delete(ud.feaplot_curcl{j}); end;
  if ((op==4)|(op==1)),
    hold on;
    delete(findobj(gca,'Tag','modelelipse'));
    plotelipses(ud.cellcl,[X1(j) Y1(j)]);
    ud.feaplot_curcl{j} = [];
    for k=1:inc,
      k,
      co = get(gca,'ColorOrder');
      ud.feaplot_curcl{j}=[ud.feaplot_curcl{j} plot(ud.fea(X{k},X1(j)),ud.fea(X{k},Y1(j)),symcl,'color',co(length(ud.cellcl)-k+1,:),...
             'MarkerSize',mscl,'Tag','FeaAxes','userdata',[X1(j) Y1(j)],'ButtonDownFcn',cb)];
    end;
    if isempty(ud.feaplot_curcl{j}), ud.feaplot_curcl{j} = -1; end;
    %if length(plotstr),
    %  eval(['ud.feaplot_curcl{j} = plot(' plotstr ',symcl,''MarkerSize'',mscl,''Tag'',''FeaAxes'',''userdata'',[X1(1) X1(2)],''ButtonDownFcn'',cb);']);
    %end;
    if exist('currinds')&length(currinds),
      ud.feaplot_curcl{j}(inc+1) =plot(ud.fea(currinds,X1(j)),ud.fea(currinds,Y1(j)),symcrcl,'MarkerSize',mscrcl,'Color',[0 0 0],...
        'Tag','FeaAxes','userdata',[X1(j) X1(j)],'ButtonDownFcn',cb);
    end;
  end;
  if ishandle(ud.feaplot_sel(j))&((length(self)==0)|(op==2)|(op==4)),disp('deleting plot');  delete(ud.feaplot_sel(j)); end;
  if ((op==2)|(op==1)|(op==4)|(op==3))&(length(self)~=0),
    hold on;
    if ~isempty(v), delete(findobj(gca,'Tag','modelelipsesel')); plotelipses({ud.cellcl{v}},[X1(j) Y1(j)],[0 0 0]); end;
    ud.feaplot_sel(j) = plot(ud.fea(self,X1(j)),ud.fea(self,Y1(j)),symsel,'MarkerSize',mssel,'Color',[0 1 0],...
        'Tag','FeaAxes','userdata',[X1(j) Y1(j)],'ButtonDownFcn',cb);
  end;
  title(titles{j});
  set(gca,'Tag','FeaAxes','userdata',[X1(j) Y1(j)],'ButtonDownFcn',cb);
end;
set(h0,'userdata',ud);

function plotelipses(cellcl,chans,col)
co = get(gca,'ColorOrder');
cb = ['disp(mat2str(findobj(gcbf,''Tag'',''okbt'')));set(findobj(gcbf,''Tag'',''okbt''),''userdata'',gcbo);uiresume(gcbf);'];
t = -pi:.01:pi;                         % angle
for i=1:length(cellcl),
   for j=1:length(cellcl{i}),
      if strcmp(cellcl{i}(j).type,'elipse'),
         x = cellcl{i}(j).params.drawmult*[sin(t);cos(t)];
         c = cellcl{i}(j).params.sqspan(chans,chans);
         ctr = cellcl{i}(j).params.center;
         [v,d] = eig(c);
         A = v*sqrt(d);
         xx = A*x;
         if nargin==2, thecol = co(length(cellcl)-i+1,:), tag='modelelipse'; else, thecol = col; tag = 'modelelipsesel'; end;
         plot(xx(1,:)+ctr(chans(1)),xx(2,:)+ctr(chans(2)),'Color',thecol,'Linewidth',[0.1],'Tag',tag,'ButtonDownFcn',cb);
      end;
   end;
end;


function gotopage(h0,spikenum,spikes)
NW = 15; n = size(spikes,2); numpages=ceil(n/NW); page = ceil(spikenum/NW);
ud = get(h0,'userdata'); ud.sppage = page; set(h0,'userdata',ud); plotspikes(h0,spikes,0); 

function plotspikes(h0,spikes,op)
NW = 15;
ud = get(h0,'userdata');

n = size(spikes,2);
set(findobj(h0,'Tag','SpikeText'),'String',['Spikes (' int2str(n) ' total): ']);
numpages = ceil(n/NW);
sppage = ud.sppage;
sel = ud.sel;

if op==Inf,sppage=numpages; elseif op==-Inf, sppage=1;
else, sppage = sppage + op; end;
if sppage<1,sppage=1;elseif sppage>numpages,sppage=numpages;end;

if sppage==numpages,
  set(findobj(h0,'Tag','forend'),'enable','off');
  set(findobj(h0,'Tag','forward'),'enable','off');
else, 
  set(findobj(h0,'Tag','forend'),'enable','on');
  set(findobj(h0,'Tag','forward'),'enable','on');
end;
if sppage==1,
  set(findobj(h0,'Tag','backend'),'enable','off');
  set(findobj(h0,'Tag','backward'),'enable','off');
else, 
  set(findobj(h0,'Tag','backend'),'enable','on');
  set(findobj(h0,'Tag','backward'),'enable','on');
end;

sp_s = (sppage~=numpages)*((sppage-1)*15+1)+...
       (sppage==numpages)*((n>=15)*(n-14)+(n<15)*1);
sp_e = min([sp_s+14 n]);

cb = ['disp(mat2str(findobj(gcbf,''Tag'',''okbt'')));set(findobj(gcbf,''Tag'',''okbt''),''userdata'',gcbo);uiresume(gcbf);'];

for i=1:(sp_e-sp_s+1),
   set(ud.ax_sp(i),'Visible','on');
   axes(ud.ax_sp(i));
   plotcsp(spikes(:,sp_s-1+i));
   L = size(spikes,1)/4;
   set(gca,'xlim',[0 L+1],'xtick',[]);
   title(int2str(sp_s-1+i));
   aud.sp = sp_s-1+i; aud.ax = i;
   set(gca,'Tag','SpikeAxes','userdata',aud,'ButtonDownFcn',cb);
   set(gca,'Color',[0.9 0.9 0.9]+(1-ud.sel(sp_s-1+i))*[0.1 0.1 0.1]);
end;

 % turn off any unused displays
for i=(sp_e-sp_s+2):15, set(ud.ax_sp(i),'Visible','off'); end;

ud.sppage = sppage;
set(h0,'userdata',ud);

function h0 = buildwindow

colororder = [  1.0, 0.0, 0.0; ...
           0.0, 1.0, 0.0; ...
           0.0, 0.0, 1.0; ...
           1.0, 1.0, 0.0; ...
           1.0, 0.0, 1.0; ...
           0.0, 1.0, 1.0; ...
           1.0, 0.7, 0.0; ...
           0.7, 1.0, 0.0; ...
           0.0, 1.0, 0.7; ...
           0.0, 0.7, 1.0; ...
           0.7, 0.0, 1.0; ...
           1.0, 0.0, 0.7; ...
           0.7, 0.0, 0.0; ...
           0.0, 0.7, 0.0; ...
           0.0, 0.0, 0.7; ...
           0.7, 0.7, 0.0; ...
           0.7, 0.0, 0.7; ...
           0.0, 0.7, 0.7];


str = which('wdcluster');
[p,n]=fileparts(str);
eval(['load ' p filesep 'graphclust ']);

cb = ['disp(mat2str(findobj(gcbf,''Tag'',''okbt'')));set(findobj(gcbf,''Tag'',''okbt''),''userdata'',gcbo),uiresume(gcbf);'];

h0 = figure('Color',[0.8 0.8 0.8], ...
        'PaperUnits','points', ...
        'Position',[69 55 1142 663], ...
        'ToolBar','none','MenuBar','none');
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','center', ...
        'Position',[323 353 120 16], ...
        'String','Cluster properties',...
        'Style','text', ...
        'Tag','StaticText8');
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'ListboxTop',0, ...
        'Position',[265.1168799212599 21.13250492125984 5.763410433070867 600.3552534448819], ...
        'Style','frame', ...
        'Tag','Frame1');
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'ListboxTop',0, ...
        'Position',[535.0366018700788 30.73818897637796 5.763410433070867 590.7495693897638], ...
        'Style','frame', ...
        'Tag','Frame1');
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'ListboxTop',0, ...
        'Position',[538.878875492126 145.0458292322835 544.6422859251969 6.723978838582678], ...
        'Style','frame', ...
        'Tag','Frame2');
ax_1x2 = axes('Parent',h0, ...
        'Units','points', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',colororder, ...
        'Position',mat2, ...
        'Tag','ax_1x2', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
axes(ax_1x2);
title('1x2');
ax_1x3 = axes('Parent',h0, ...
        'Units','points', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',colororder, ...
        'Position',mat6, ...
        'Tag','ax_1x3', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
axes(ax_1x3);
title('1x3');
ax_1x4 = axes('Parent',h0, ...
        'Units','points', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',colororder, ...
        'Position',mat9, ...
        'Tag','ax_1x4', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
axes(ax_1x4);
title('1x4');
ax_2x3 = axes('Parent',h0, ...
        'Units','points', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',colororder, ...
        'Position',mat12, ...
        'Tag','ax_2x3', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
axes(ax_2x3);
title('2x3');
ax_2x4 = axes('Parent',h0, ...
        'Units','points', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',colororder, ...
        'Position',mat15, ...
        'Tag','ax_2x4', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
axes(ax_2x4);
title('2x4');
ax_3x4 = axes('Parent',h0, ...
        'Units','points', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',colororder, ...
        'Position',mat18, ...
        'Tag','ax_3x4', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
axes(ax_3x4);
title('3x4');
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8 ], ...
        'FontSize',14, ...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[565.7747908464568 121.9921875 151.7698080708662 17.2902312992126], ...
        'String','WD cluster list', ...
        'Style','text', ...
        'Tag','StaticText1');
lb = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'Position',[546.5634227362206 31.69875738188977 189.2319758858268 82.60888287401576], ...
        'Style','List', 'String',{'clust1'},...
        'Tag','lb','Callback',cb);
newbt = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[745.4010826771654 120.0710506889764 78.7666092519685 17.2902312992126], ...
        'String','New', ...
        'Tag','newbt','Callback',cb);
deletebt = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[745.4010826771654 97.97797736220474 78.7666092519685 17.2902312992126], ...
        'String','Delete', ...
        'Tag','deletebt','Callback',cb);
okbt = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[992.2671628937009 35.54103100393701 73.00319881889764 28.81705216535433], ...
        'String','OK', ...
        'Tag','okbt','Callback',cb);
ax_key = axes('Parent',h0, ...
        'Units','points', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat20, ...
        'Position',[930 328 19 100], ...
        'Tag','ax_key', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[958 420 73 15], ...
        'String','Key:', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[958 398 73 15], ...
        'String','unclustered pt', ...
        'Style','text', ...
        'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[958 378 73 15], ...
        'String','selected pt', ...
        'Style','text', ...
        'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[958 358 73 15 ], ...
        'String','clustered pt', ...
        'Style','text', ...
        'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[958 338 73 15 ], ...
        'String','curr clust pt', ...
        'Style','text', ...
        'Tag','StaticText3');
ms={'1','2','3','4','5','6','7','8','9','10'};
ms_uncl = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Min',1, ...
        'Position',mat22, ...
        'String',ms, ...
        'Style','popupmenu', ...
        'Tag','ms_uncl', ...
        'Value',1,'Callback',cb);
sym = {'.','o','x','+','*','s','d','v','^','<','>','p','h'};
sym_uncl = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Min',1, ...
        'Position',mat23, ...
        'String', sym, ...
        'Style','popupmenu', ...
        'Tag','sym_uncl', ...
        'Value',1,'Callback',cb);
ms_sel = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Min',1, ...
        'Position',mat24, ...
        'String',ms, ...
        'Style','popupmenu', ...
        'Tag','ms_sel', ...
        'Value',1,'Callback',cb);
ms_cl = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Min',1, ...
        'Position',mat25, ...
        'String',ms, ...
        'Style','popupmenu', ...
        'Tag','ms_cl', ...
        'Value',1,'Callback',cb);
sym_sel = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Min',1, ...
        'Position',mat26, ...
        'String',sym, ...
        'Style','popupmenu', ...
        'Tag','sym_sel', ...
        'Value',1,'Callback',cb);
sym_cl = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Min',1, ...
        'Position',mat27, ...
        'String',sym', ...
        'Style','popupmenu', ...
        'Tag','sym_cl', ...
        'Value',1,'Callback',cb);
sym_ccl = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Min',1, ...
        'Position',[1061 337 20 14 ], ...
        'String',sym', ...
        'Style','popupmenu', ...
        'Tag','sym_ccl', ...
        'Value',1,'Callback',cb);
ms_ccl = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Min',1, ...
        'Position',[1036 337 20 14], ...
        'String',ms, ...
        'Style','popupmenu', ...
        'Tag','ms_ccl', ...
        'Value',5,'Callback',cb);
ax_sel1 = axes('Parent',h0, ...
        'Units','points', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat28, ...
        'Position',[294 470 110 100 ], ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0],'YAxisLocation','left');
%axes(ax_sel1);plot(randn(100,1));
ax_sel2 = axes('Parent',h0, ...
        'Units','points', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat28, ...
        'Position',[404 470 110 100 ], ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0],'YAxisLocation','left');
%axes(ax_sel2);plot(randn(100,1));
ax_sel3 = axes('Parent',h0, ...
        'Units','points', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat28, ...
        'Position',[294 370 110 100 ], ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0],'YAxisLocation','left');
%axes(ax_sel3);plot(randn(100,1));
ax_sel4 = axes('Parent',h0, ...
        'Units','points', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat28, ...
        'Position',[404 370 110 100 ], ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0],'YaxisLocation','right');
%axes(ax_sel4);plot(randn(100,1));
y = 350;
ax_cl1 = axes('Parent',h0, ...
        'Units','points', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat28, ...
        'Position',[294 470-y 110 100 ], ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0],'YAxisLocation','left');
%axes(ax_cl1);plot(randn(100,1));
ax_cl2 = axes('Parent',h0, ...
        'Units','points', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat28, ...
        'Position',[404 470-y 110 100 ], ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0],'YAxisLocation','left');
%axes(ax_cl2);plot(randn(100,1));
ax_cl3 = axes('Parent',h0, ...
        'Units','points', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat28, ...
        'Position',[294 370-y 110 100 ], ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0],'YAxisLocation','left');
%axes(ax_cl3);plot(randn(100,1));
ax_cl4 = axes('Parent',h0, ...
        'Units','points', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat28, ...
        'Position',[404 370-y 110 100 ], ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0],'YaxisLocation','right');
%axes(ax_cl4);plot(randn(100,1));
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontSize',14, ...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[343 600 115 16], ...
        'String','Selected spikes:', ...
        'Style','text', ...
        'Tag','StaticText4');
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontSize',12, ...
        'ListboxTop',0, ...
        'Position',[343 580 115 16], ...
        'String','', ...
        'Style','PushButton', ...
        'Tag','selectedtext','Callback',cb);
clustlb = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'Position',[283 265 200  90], ...
        'Style','List','String',{},...
        'Tag','clustlb');
newclprop = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[485 340 40 16], ...
        'String','New', ...
        'Tag','newclprop','Callback',cb);
h1= uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[485 320 40 16], ...
        'String','Edit', ...
        'Tag','editclprop','Callback',cb);
h1= uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[485 300 40 16], ...
        'String','Delete', ...
        'Tag','deleteclprop','Callback',cb);
burst = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[285.2888164370079 241.1026697834646 67.23978838582678 19.21136811023622], ...
        'String','Burster', ...
        'Style','checkbox', ...
        'Tag','burster','Callback',cb);
garbage = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[355.4103100393701 241.1026697834646 97.01740895669292 19.21136811023622], ...
        'String','Garbage cluster', ...
        'Style','checkbox', ...
        'Tag','garbage','Callback',cb);
addcl = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontSize',12, ...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[455 242 70 18], ...
        'String','Sel. clust', ...
        'Tag','selcluster','Callback',cb);
forward = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[140.6373031496063 34.5804625984252 38.42273622047244 18.25079970472441], ...
        'String','->', ...
        'Tag','forward','Callback',cb);
forend = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',mat42, ...
        'String','->|', ...
        'Tag','forend','Callback',cb);
backward = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[97.21456692913387 34.5804625984252 38.42273622047244 18.25079970472441], ...
        'String','<-', ...
        'Tag','backward','Callback',cb);
backend = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[53.79183070866142 34.5804625984252 38.42273622047244 18.25079970472441], ...
        'String','|<-', ...
        'Tag','backend','Callback',cb);

h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontSize',14, ...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[70 596.5129798228347 140 16.32966289370079], ...
        'String','Spikes:', ...
        'Style','text', ...
        'Tag','SpikeText');
ax_sp(1) = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat43, ...
        'Position',[25 503 63 80], ...
        'Tag','ax_sp', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0],'ButtonDownFcn',cb);
axes(ax_sp(1));title('1');
ax_sp(2) = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat45, ...
        'Position',[110 502 63 80], ...
        'Tag','ax_sp', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0],'ButtonDownFcn',cb);
axes (ax_sp (2)); title ('2');
ax_sp(3) = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat46, ...
        'Position',[198 502 63 80], ...
        'Tag','ax_sp', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
axes(ax_sp(3));title('3');
ax_sp(6) = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat47, ...
        'Position',[198 403 63 80], ...
        'Tag','ax_sp', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
axes(ax_sp(6));title('6');
ax_sp(5) = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat48, ...
        'Position',[110 403 63 80], ...
        'Tag','ax_sp', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
axes(ax_sp(5));title('5');
ax_sp(4) = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat49, ...
        'Position',[25 404 63 80], ...
        'Tag','ax_sp', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
axes(ax_sp(4));title('4');
ax_sp(7) = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat50, ...
        'Position',[25 305 63 80], ...
        'Tag','ax_sp', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
axes(ax_sp(7));title('7');
ax_sp(8) = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat52, ...
        'Position',[110 304 63 80], ...
        'Tag','ax_sp', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
axes(ax_sp(8));title('8');
ax_sp(9) = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat54, ...
        'Position',[198 304 63 80], ...
        'Tag','ax_sp', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
axes(ax_sp(9));title('9');
ax_sp(12) = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat56, ...
        'Position',[198 206 63 80], ...
        'Tag','ax_sp', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
axes(ax_sp(12));title('12');
ax_sp(11) = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat57, ...
        'Position',[110 206 63 80], ...
        'Tag','ax_sp', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
axes(ax_sp(11));title('11');
ax_sp(10) = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat58, ...
        'Position',[25 207 63 80], ...
        'Tag','ax_sp', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
axes(ax_sp(10));title('10');
ax_sp(13) = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat59, ...
        'Position',[25 108 63 80], ...
        'Tag','ax_sp', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
axes(ax_sp(13));title('13');
ax_sp(14) = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat61, ...
        'Position',[110 107 63 80], ...
        'Tag','ax_sp', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
axes(ax_sp(14));title('14');
ax_sp(15) = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat63, ...
        'Position',[198 107 63 80], ...
        'Tag','ax_sp', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
axes(ax_sp(15));title('15');
redisplay = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[745.4010826771654 34.5804625984252 130.6373031496063 21.13250492125984], ...
        'String','Redisplay if data added', ...
        'Style','checkbox', ...
        'Tag','redisplay','Callback',cb,'Value',1);
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[742 560 45 16], ...
        'String','Clicking:', ...
        'Style','text', ...
        'Tag','StaticText8');
clickmenu = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Min',1, ...
        'Position',[792 561 75 18],...
        'String',{'zooms','selects'}, ...
        'Style','popupmenu', ...
        'Tag','feaclickmenu', ...
        'Value',1,'Callback',cb);
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[742 540 85 16], ...
        'String','Selection method:', ...
        'Style','text', ...
        'Tag','StaticText8');
h1 = uicontrol('Parent',h0,...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[742 520 85 16], ...
        'String','Num pts selected:', ...
        'Style','text', ...
        'Tag','StaticText8');
h1 = uicontrol('Parent',h0,...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[825 520 85 16], ...
        'String','0', ...
        'Style','text', ...
        'Tag','numptssel');
feaselectmenu= uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Min',1, ...
        'Position',[825 541 75 18],...
        'String',{'circle','polygon'}, ...
        'Style','popupmenu', ...
        'Tag','feaselectmenu', ...
        'Value',1,'Callback',cb);
selecthelptext = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[742 504 250 32], ...
        'String','', ...
        'Style','text', ...
        'Tag','selecthelptext');
deselectfea = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[742 485 60 16], ...
        'String','Deselect All', ...
        'Tag','deselectfea','Callback',cb);
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontSize',12, ...
        'ListboxTop',0, ...
        'Position',[344 220 115 16], ...
        'String','Clustered spikes:', ...
        'Style','text', ...
        'Tag','StaticText4');
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontSize',12, ...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[735.7953986220473 595.5524114173229 76.84547244094489 15.36909448818898], ...
        'String','Feature:', ...
        'Style','text', ...
        'Tag','StaticText9');
featuremenu = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Min',1, ...
        'Position',[818.404281496063 593.6312746062993 97.01740895669292 20.17193651574803], ...
        'String',{'Peaks','V at Max E'}, ...
        'Style','popupmenu', ...
        'Tag','featuremenu', ...
        'Value',1,'Callback',cb);
h1 = uicontrol('Parent',h0,...
         'Units','points', ...
         'BackgroundColor',[0.8 0.8 0.8], ...
         'ListboxTop',0, ...
         'FontWeight','normal', 'FontSize',10, ...
         'Position',[10 73 45 18], ...
         'String','Clicking:',...
         'Style','Text');
clickmenu = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Min',1, ...
        'Position',[55 75 75 18],...
        'String',{'zooms','selects','gives info','shows data'}, ...
        'Style','popupmenu', ...
        'Tag','spclickmenu', ...
        'Value',1,'Callback',cb);
h1 = uicontrol('Parent',h0,...
         'Units','points', ...
         'BackgroundColor',[0.8 0.8 0.8], ...
         'ListboxTop',0, ...
         'FontWeight','normal', 'FontSize',10, ...
         'Position',[135 55 120 40], ...
         'String','Spike Info:',...
         'Style','Text','Tag','spinfo');
deselect = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[13 58 60 16], ...
        'String','Deselect all', ...
        'Tag','deselect','Callback',cb);

set(h0,'userdata',struct('ax_sel',[ax_sel1 ax_sel2 ax_sel3 ax_sel4],'ax_cl',[ax_cl1 ax_cl2 ax_cl3 ax_cl4],...
          'ax_sp',ax_sp,'ax_1x2',ax_1x2,'ax_1x3',ax_1x3,'ax_1x4',ax_1x4,'ax_2x3',ax_2x3,'ax_2x4',ax_2x4,...
          'ax_3x4',ax_3x4,'ax_key',ax_key,'sel',[],'cellcl',{{[]}},'cl',[],'sppage',1,'okbt',okbt,...
          'sel_plt',[],'feaplot_uncl',[],'fea',[],'feaplot_sel',[],'feaplot_cls',{{}},'selcl',[],...
          'feaplot_curcl',[],'cellclstr',{{'clust1'}})); 
