function newmdd = setparameters(mdd,parameters)

%  NEWMDD = SETPARAMETERS(MDD,P)
%
%  Sets the parameters of the MEASUREDDATADISPLAY object MDD to P.  P must be a
%  valid set of parameters.  The outputs and menus of MDD are re-computed and
%  re-displayed.
%  If P is the string 'default' then the default parameters are chosen.
%
%  See also:  MEASUREDDATADISPLAY, GETPARAMETERS

color = [  1.0, 0.0, 0.0; ...
           0.0, 1.0, 0.0; ...
           0.0, 0.0, 1.0; ...
           1.0, 1.0, 0.0; ...
           1.0, 0.0, 1.0; ...
           0.0, 1.0, 1.0; ...
           1.0, 0.7, 0.0; ...
           0.7, 1.0, 0.0; ...
           0.0, 1.0, 0.7; ...
           0.0, 0.7, 1.0; ...
           0.7, 0.0, 1.0; ...
           1.0, 0.0, 0.7; ...
           0.7, 0.0, 0.0; ...
           0.0, 0.7, 0.0; ...
           0.0, 0.0, 0.7; ...
           0.7, 0.7, 0.0; ...
           0.7, 0.0, 0.7; ...
           0.0, 0.7, 0.7];

oldmdd = mdd; 

defstr = struct('sepmeth',0,'sepdist',1.2,'line',1,'linesz',1,...
                'sym','.','markerSize',1,...
                'scaling',1,'color',color(1,:),'draw',1);

default_p = struct('displayParams',defstr,'offset',1,'memwarning',100,...
             'xaxis','auto','yaxis','auto','xauto',[0 10],'removemeans',1,...
             'lineatzero',1,'lineatzerosz',1);
for i=1:length(mdd.inputs.measureddata),
   defstr.color = color(i,:); default_p.displayParams(i) = defstr;
end;

if isempty(parameters)|(ischar(parameters)&strcmp(parameters,'default')),
        parameters = default_p; end;

[good,er]=verifyparameters(parameters);if ~good,error(['PARAMETERS: ' er]);end;

mdd.MDDparams = parameters;
mdd = compute(mdd);
t=draw(mdd);
if t==0,
  mdd = oldmdd;
  draw(mdd);
end;
configuremenu(mdd);
newmdd = mdd;

