function clustergraph(features,color)
%CLUSTERGRAPH shows graphs of all FEATURES plotted against all other FEATURES
%
%    CLUSTERGRAPH(FEATURES,COLOR) 
%      size(FEATURES)=[number of spikes,number of features]
%
%      FEATURES can be loaded from features.asc files generated by 
%      spike2cell by e.g. features=load('tet1.features.asc','-ascii'); 
%
%    March 2001, Alexander Heimel (heimel@brandeis.edu)
%
%

if nargin<2
  color='b';
end

features=features';

figure;
n_features=size(features,1);
for r=2:n_features
  for c=1:r-1
    subplot(n_features-1,n_features-1,c+(r-2)*(n_features-1))
    plot(features(c,:),features(r,:),['.' color],'markersize',1)
    % axis([-60 60 -60 60])
    
  end
end
