function generate_contra_ipsi_correlation
%GENERATE_CONTRA_IPSI_CORRELATION generates for our BXD-mice a sample with
%a correlation between contra and ipsi shift to see if we could detect a
%correlation
%
% undeprived contra and ipsi strain values are taken from data
% abs deprived contra and ipsi values is taken as a percentage of B6 shift
% and data generated by a normal distribution with SE from data
% then correlation is calculated and significance measured
% this is done X times and the percentage of significant outcomes is the
% power of our test
%
% 2008, Alexander Heimel
%


contra_undeprived=[0.33 0.15 0.26 0.30 0.27 0.30 0.20 0.26 0.33 0.21 0.27 0.30 0.24]';
ipsi_undeprived  =[0.14 0.06 0.12 0.08 0.13 0.11 0.06 0.12 0.16 0.10 0.11 0.10 0.10]';



contra_deprived=[0.25 0.12 0.17 0.35 0.20 0.29 0.13 0.20 0.24 0.17 0.28 0.24 0.25]';
ipsi_deprived=[0.24 0.09 0.16 0.07 0.18 0.19 0.10 0.08 0.20 0.16 0.19 0.17 0.16]';

contra_shifts=contra_deprived-contra_undeprived
ipsi_shifts=ipsi_deprived-ipsi_undeprived


contra_deprived_sem=[0.07 0.03 0.02 0.03 0.06 0.03 0.02 0.03 0.03 0.04 0.01 0.04 0.02];
ipsi_deprived_sem=[0.06 0.02 0.04 0.04 0.05 0.04 0.01 0.01 0.03 0.03 0.02 0.03 0.02];

contra_deprived_sem=mean(contra_deprived_sem);
ipsi_deprived_sem=mean(ipsi_deprived_sem);

n_strains=13; % real number is 13

n_tries=100;
n_significant_abs=0;
n_significant_rel=0;

b6_shift_contra=-0.073;
b6_shift_ipsi=0.10;

mean_shift_contra=mean( contra_deprived-contra_undeprived)
mean_shift_ipsi=mean( ipsi_deprived-ipsi_undeprived)
std_shift_contra=std( contra_deprived-contra_undeprived)
std_shift_ipsi=std( ipsi_deprived-ipsi_undeprived)

overall_plasticity_factor=1;

for i=1:n_tries
	%overall_plasticity=overall_plasticity_factor*rand(n_strains,1); % shifts are flat distribution between 0 and 1

	overall_plasticity=overall_plasticity_factor*random('norm',0,1,n_strains,1); 
	%sliding_threshold=sliding_threshold_factor*random('norm',n_strains,1);
	%shifts_contra=overall_plasticity*b6_shift_contra;
	%shifts_ipsi=overall_plasticity*b6_shift_ipsi;
	shifts_contra=mean_shift_contra + std_shift_contra*overall_plasticity;
	shifts_ipsi=mean_shift_ipsi - std_shift_ipsi*overall_plasticity;
	
	noise_contra=random('norm',0,contra_deprived_sem,n_strains,1);
	abs_shifts_contra=shifts_contra+noise_contra;
	noise_ipsi=random('norm',0,ipsi_deprived_sem,n_strains,1);
	abs_shifts_ipsi=shifts_ipsi+noise_ipsi;

	rel_shifts_contra=abs_shifts_contra./contra_undeprived;
	rel_shifts_ipsi=abs_shifts_ipsi./ipsi_undeprived;
	
	[r,n,p]=nancorrcoef(abs_shifts_contra,abs_shifts_ipsi);
	if p<0.05 % in paper 0.6 %p<0.05
		n_significant_abs=n_significant_abs+1;
	end
	[r,n,p]=nancorrcoef(rel_shifts_contra,rel_shifts_ipsi);
	if p<0.05 % in paper p<0.8 %p<0.05
		n_significant_rel=n_significant_rel+1;
	end
	
end
r
p
plot(abs_shifts_contra,abs_shifts_ipsi,'x')

disp(['Fraction of significant abs shift correlation trials: ' num2str(n_significant_abs/n_tries,2) ]);
disp(['Fraction of significant rel shift correlation trials: ' num2str(n_significant_rel/n_tries,2) ]);


