function rr = tp_emptyroirec(record)
%TP_EMPTYROIREC contains structure of a ROI for analyzetpstack
%
% if necessary use ORDERFIELDS( ROILIST, TP_EMPTYROIREC) to use order
%
% 2011, Alexander Heimel
%

if nargin<1
    n_channels = 2;
else
    params = tpreadconfig(record);
    n_channels = params.NumberOfChannels;

end

rr = struct( ...
    'index',[], ...
    'present',1, ...
    'type','', ...  % check tpstacktypes for options
    'labels','', ...  % check tpstacklabels for options
    'neurite',[NaN inf], ...
    'dirname','', ...
    'intensity_mean',NaN*ones(1,n_channels), ...
    'intensity_max',NaN*ones(1,n_channels), ...
    'intensity_rel2dendrite',NaN*ones(1,n_channels), ...
    'intensity_rel2synapse',NaN*ones(1,n_channels), ...
    'intensity_rank',NaN*ones(1,n_channels), ...
    'pixelinds',[], ...
    'xi',[], ...
    'yi',[], ...
    'zi',[], ...
    'dimensions',2, ... % i.e. 0 = point, 1 = line, 2 = area, 3 = volume
    'extra',[] ...  % should be last element for exporting csv, because if it is a struct, its length may be variable
    );