function fig = lgnctx_extinfo()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load lgnctx_extinfo

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[768 516 402 330], ...
	'Tag','Fig1', ...
	'ToolBar','none');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[24 283 144 17], ...
	'String','Extracellular cell info:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','genercallback', ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[57 43 89 20], ...
	'String','Save', ...
	'Tag','ExtCellSaveBt');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',9, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[16 244 99 17], ...
	'String','Optic disks:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[169 202 41 20], ...
	'Style','edit', ...
	'Tag','MonPosXEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[59 203 41 20], ...
	'Style','edit', ...
	'Tag','leftVertEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[59 179 41 20], ...
	'Style','edit', ...
	'Tag','rightVertEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[104 179 41 20], ...
	'Style','edit', ...
	'Tag','rightHortEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[104 202 41 20], ...
	'Style','edit', ...
	'Tag','leftHortEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[57 224 34 17], ...
	'String','Vert:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[109 223 34 17], ...
	'String','Hort:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[18 204 34 17], ...
	'String','left', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[19 179 34 17], ...
	'String','right:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',9, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[159 245 99 17], ...
	'String','Monitor position:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[224 227 34 17], ...
	'String','Y:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[172 227 34 17], ...
	'String','X:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[275 227 34 17], ...
	'String','Z:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[224 202 41 20], ...
	'Style','edit', ...
	'Tag','MonPosYEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[274 203 41 20], ...
	'Style','edit', ...
	'Tag','MonPosZEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','genercallback', ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[44 155 89 20], ...
	'String','Get from screentool', ...
	'Tag','GetODLocsBt');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','genercallback', ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[197 175 89 20], ...
	'String','Get from screentool', ...
	'Tag','GetMonPosBt');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[20 131 34 18], ...
	'String','Depth:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[81 129 80 20], ...
	'Style','edit', ...
	'Tag','DepthEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[19 102 55 18], ...
	'String','Hemisphere:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Min',1, ...
	'Position',[83 105 73 17], ...
	'String','left', ...
	'Style','popupmenu', ...
	'Tag','HemispherePopup', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Min',1, ...
	'Position',[266 134 101 17], ...
	'String','ipsi completely', ...
	'Style','popupmenu', ...
	'Tag','EyePopup', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[182 129 73 18], ...
	'String','Eye dominance:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[22 262 250 17], ...
	'String',':', ...
	'Style','text', ...
	'Tag','CellInfoStatic');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','genercallback', ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[174 40 89 20], ...
	'String','Load', ...
	'Tag','ExtCellRestoreBt');
if nargout > 0, fig = h0; end
