function plothandles=slideplot(data,showr,showc,range)
%SLIDEPLOT to show array of graphs with slidebars to position them
%
%  HANDLES=SLIDEPLOT(DATA,[SHOWR=3],[SHOWC=4],[RANGE])
%   last two dimensions of DATA are used as row and column position
%   SHOWR is number of rows to be shown
%   SHOWC is number of cols to be shown
%   if there are less rows of columns in the data, SHOWR and SHOWC get adjusted
%   RANGE is output range for plots.
%   handles is matrix of axes handle 
%
%  Jan 2002, Alexander Heimel
%


h0=figure;

rows= size( data, size(size(data),2) ); 
cols= size( data,size(size(data),2)-1) ;


ud=struct('rows',rows,'cols',cols);

ud.showc=4;
ud.showr=3;

if(nargin>1)
  ud.showr=showr;
end
if(nargin>2)
  ud.showc=showc;
end

if rows<ud.showr, ud.showr=rows; end;
if cols<ud.showc, ud.showc=cols; end;

ud.w=0.9/ud.showc;
ud.h=0.9/ud.showr;

for r=1:rows
  for c=1:cols
    subplot(rows,cols,(c-1)*rows+r);
    if size(size(data),2)==3, plot(data(:,c,r)), end;
    if size(size(data),2)==4, plot(data(:,:,c,r)), end;
    if nargin==4, axis(range); end;
    plothandles(r,c)=gca;
  end
end

for r=1:rows
  for c=1:cols
    set(plothandles((r-1)*cols+c),'Position',[0.1+(c-1)*ud.w-0*ud.w*(ud.cols-ud.showc) ...
    -1*ud.h*(ud.rows-ud.showr)+0.1+(r-1)*ud.h  0.85*ud.w 0.75*ud.h]);
  end
end

ud.plothandles=plothandles;

if(cols>ud.showc)
  pos=get(h0,'Position');
  if rows>ud.showr, pos=[18 0 pos(3)-18 20]; else pos=[0 0 pos(3) 20]; end
  hhor=uicontrol(gcf,'Style','slider','Position',pos,...
	     'Min',0,'Max',1,'Value',0);
ud.hhor=hhor;
end

if(rows>ud.showr)
  pos=get(h0,'Position');
  if cols>ud.showc, pos=[0 18 20 pos(4)-18]; else pos=[0 0 20 pos(4)]; end
  hver=uicontrol(gcf,'Style','slider','Position',pos,...
	     'Min',0,'Max',1,'Value',1);
ud.hver=hver;
end

set(h0,'ResizeFcn',[ ...
   'if exist(''resizepos'') error(''ResizeFcn: Variable resizepos already exists.''); end;'...
   'if exist(''resizeud'') error(''ResizeFcn: Variable resizeud already exists.''); end;'...
   'resizepos=get(gcf,''Position''); resizeud=get(gcf,''UserData'');'...
   'if isfield(resizeud,''hhor''),'...
      'if exist(''resizehpos'') error(''ResizeFcn: Variable resizehpos already exists.''); end;'...
      'resizehpos=get(resizeud.hhor,''Position'');resizehpos(3)=resizepos(3)-resizehpos(1); '...
      'set(resizeud.hhor,''Position'',resizehpos);clear(''resizehpos'');'...
   'end;',...
   'if isfield(resizeud,''hver''),'...
      'if exist(''resizevpos'') error(''ResizeFcn: Variable resizevpos already exists.''); end;'...
       'resizevpos=get(resizeud.hver,''Position'');resizevpos(4)=resizepos(4)-resizevpos(2); '...
      'set(resizeud.hver,''Position'',resizevpos);clear(''resizevpos'');'...
   'end;clear(''resizepos'');clear(''resizeud'');'...
   ]);


set(h0,'UserData',ud);

if(cols>ud.showc)
  set(hhor,'CallBack', [...
   'if exist(''moveud'') error(''CallBack: Variable moveud already exists.''); end;'...
   'if exist(''movepos'') error(''CallBack: Variable movepos already exists.''); end;'...
   'if exist(''moveh'') error(''CallBack: Variable moveh already exists.''); end;'...
   'if exist(''movec'') error(''CallBack: Variable movec already exists.''); end;'...
   'if exist(''mover'') error(''CallBack: Variable mover already exists.''); end;'...
   'moveud=get(gcf,''UserData''); ' ...
   'for mover=1:moveud.rows;for movec=1:moveud.cols;'...
   'moveh=moveud.plothandles((mover-1)*moveud.cols+movec);' ...
   'movepos=get(moveh,''Position'');'...
   'movepos(1)=-(get(moveud.hhor,''Value''))*moveud.w*(moveud.cols-moveud.showc)+moveud.w*(movec-1)+0.1;' ...
   'set(moveh,''Position'',movepos);' ...
   'end; end;clear(''moveud'',''movepos'',''moveh'',''movec'',''mover'');' ...
   ])
end

if(rows>ud.showr)
  set(hver,'CallBack', [...
   'if exist(''movepos'') error(''CallBack: Variable movepos already exists.''); end;'...
   'if exist(''moveud'') error(''CallBack: Variable moveud already exists.''); end;'...
   'if exist(''moveh'') error(''CallBack: Variable moveh already exists.''); end;'...
   'if exist(''movec'') error(''CallBack: Variable movec already exists.''); end;'...
   'if exist(''mover'') error(''CallBack: Variable mover already exists.''); end;'...
   'moveud=get(gcf,''UserData''); ' ...
   'for mover=1:moveud.rows;for movec=1:moveud.cols;'...
   'moveh=moveud.plothandles((mover-1)*moveud.cols+movec);' ...
   'movepos=get(moveh,''Position''); '...
   'movepos(2)=-(get(moveud.hver,''Value''))*moveud.h*(moveud.rows-moveud.showr)+moveud.h*(mover-1)+0.1;' ...
   'set(moveh,''Position'',movepos);' ...
   'end; end;clear(''moveud'',''movepos'',''moveh'',''movec'',''mover'')' ...
  ])
end

