function b = transferscripts(scriptnames,scriptlist) %#ok<INUSD>

%  TRANSFERSCRIPTS - Transfers scripts to remote stimulus computer
%
%  B = TRANSFERSCRIPTS(SCRIPTNAMES,SCRIPTLIST)
%
%  Accepts a cell list of script names (SCRIPTNAMES) and the variables
%  (SCRIPTLIST), and transfers them to the remote computer.  The stimuli
%  or scripts are then loaded.

NewStimGlobals;

b = checkremotedir(NewStimRemoteCommDir);
if ~b, return; end;

biglist = [];
for i=1:length(scriptnames),
  eval([scriptnames{i} '=scriptlist{i};']);
  biglist = [biglist ' ''' scriptnames{i} ''','];
end;
if ~isempty(biglist), biglist = biglist(1:end-1); end;
pathn = fixpath(NewStimRemoteCommDir);
fname = [pathn 'toremote.mat'];  %#ok<NASGU>
eval(['save (fname,' biglist ',''-v6'');']);


strs = {      'names=load(''toremote.mat'',''-mat'');fnames=fieldnames(names);'...
             'finished=zeros(1,length(fnames));'...
             'for i=1:length(fnames),'...
               'if exist(fnames{i})==1,'...
                 'eval([''b1=isa('' fnames{i} '', ''''stimscript'''');'']);'...
                 'eval([''b2=isa('' fnames{i} '', ''''stimulus'''');'']);'...
                 'if b1|b2,'...
                    'eval([''b3 = '' fnames{i} '' == names.'' fnames{i} '';'']);'...
                    'eval([''b3 = b3&isloaded('' fnames{i} '');'']);'...
                    'if ~b3,'...
                      'if b1,'...
                        'eval([fnames{i} '' = unloadStimScript('' fnames{i} '');'']);'...
                      'else,'...
                        'eval([fnames{i} '' = unloadstim('' fnames{i} '');'']);'...
                      'end;'...
                    'else, finished(i) = 1;'...
                    'end;'...
                 'end;'...
               'end;'...
               'if finished(i)~=1,'...
                 'eval([''b1=isa(names.'' fnames{i} '', ''''stimscript'''');'']);'...
                 'eval([''b2=isa(names.'' fnames{i} '', ''''stimulus'''');'']);'...
                 'if b1,'...
                    'eval([fnames{i} ''=loadStimScript(names.'' fnames{i} '');'']);'...
                 'elseif b2,'...
                    'eval([fnames{i} ''=loadstim(names.'' fnames{i} '');'']);'...
                 'end;'...
                 'finished(i)=1;'...
               'end;'...
             'end;'...
             'save(''gotit.mat'',''fnames'',''-mat'');',...   
             'save(''fromremote.mat'',''fnames'',''-mat'');'};    
                   
b = sendremotecommand(pathn,strs);
if b,
  dowait(1);
  thefig = geteditor('RemoteScriptEditor');
  if isempty(thefig), RemoteScriptEditor; else, RemoteScriptEditor('Update',thefig); end;
end;
