function [css] = centersurroundstim(CSSp, OLDSTIM)

%  NewStim package:  CENTERSURROUNDSTIM
%
%  THECSS = CENTERSURROUNDSTIM(PARAMETERS)
%
%  Creates a centersurroundstim object.  A centersurroundstim draws a circular
%  spot on the screen optionally surrounded by an additional circle.  That is,
%  it presents stimuli which look like prototypical receptive fields for the 
%  mammalian lateral geniculate nucleus.  The surround can be presented at
%  a latency offset from the center.
%
%  PARAMETERS can either be the string 'graphical' (which will prompt the user
%  to enter all of the parameter values), the string 'default' (which will
%  use default parameter values), or a structure.  When using 'graphical', one
%  may also use
%
%  CSS = CENTERSURROUNDSTIM('graphical',OLDCSS)
%
%  where OLDCSS is a previously created centersurroundstim object.  This will
%  set the default parameter values to those of OLDCSS.
%
%  If passing a structure, the structure should have the following fields:
%  (dimensions of parameters are given as [M N]; fields are case-sensitive):
%
%  [1x2] center       - Location of center of circles [x y]
%  [1x1] radius       - Radius of center circle
%  [1x1] surrradius   - Radius of surround (or -1 if none)
%  [1x3] BG           - Background color [r g b]
%  [1x3] FGc          - Color of center [r g b]
%  [1x3] FGs          - Color of surround [r g b]
%  [1x1] contrast     - Actual colors shown in FGc, FGs will be adjusted so
%                         they are this fraction [0..1] between FGc and FGs.
%  [1x1] lagon        - Lag between start of stimulus and presentation of
%                         center (in seconds)
%  [1x1] lagoff       - Lag between start of stimulus and resumption of bg
%                         in center (-1 for never) (in seconds)
%  [1x1] surrlagon    - Lag between start of stimulus and presentation of
%                         surround (in seconds)
%  [1x1] surrlagoff   - Lag between start of stimulus and resumption of bg
%                         in surround (-1 for never) (in seconds)
%  [1x1] stimduration - Total stimulus duration (in seconds)
% [cell] dispprefs    - Sets displayprefs fields, or use {} for default values.
%
%   Questions to vanhoosr@brandeis.edu

NewStimListAdd('centersurroundstim');

if nargin==0,
	css = centersurroundstim('default');
	return;
end;

default_p = struct ( 'center', [100 100], 'BG', 128*[1 1 1], 'FGc',255*[1 1 1],...
                     'FGs',0*[1 1 1],'contrast',1,'lagon',0,'lagoff',-1,...
                     'surrlagon',0,'surrlagoff',-1,'radius',50,'surrradius',-1,...
                     'stimduration',0.5);
default_p.dispprefs = {};
finish = 1;

if nargin==1, oldstim=[]; else, oldstim = OLDSTIM; end;

if ischar(CSSp),
	if strcmp(CSSp,'graphical'),
		% load parameters graphically, check values
		p = get_graphical_input(oldstim);
		if isempty(p), finish = 0; else, CSSp = p; end;
	elseif strcmp(CSSp,'default'),
		CSSp = default_p;
	else,
		error('Unknown string input to centersurroundstim.');
	end;
else,  % they are just parameters
	[good, err] = verifycentersurroundstim(CSSp);
	if ~good, error(['Could not create centersurround: ' err]); end;
end;

if finish,
        if haspsychtbox,StimWindowGlobals;fps=StimWindowRefresh; else,fps=-1; end;
        biggestrad = max([CSSp.radius CSSp.surrradius]);
        rect = [ CSSp.center-biggestrad CSSp.center+biggestrad];
	dp = {'fps',fps, 'rect',rect, 'frames', 4, CSSp.dispprefs{:}};
	s = stimulus(5);
	css = class(struct('CSSparams',CSSp),'centersurroundstim',s);
	css.stimulus = setdisplayprefs(css.stimulus,displayprefs(dp));
else,
	css = [];
end;

function params = get_graphical_input(oldstim)

if isempty(oldstim), oldstim=centersurroundstim('default'); end;

oldsP = struct(oldstim);
CSSparams = oldsP.CSSparams;
center_str = mat2str(CSSparams.center);
bg_str = mat2str(CSSparams.BG);
FGc_str = mat2str(CSSparams.FGc);
FGs_str = mat2str(CSSparams.FGs);
contrast_str = num2str(CSSparams.contrast);
lagon_str = num2str(CSSparams.lagon);
lagoff_str = num2str(CSSparams.lagoff);
surrlagon_str = num2str(CSSparams.surrlagon);
surrlagoff_str = num2str(CSSparams.surrlagoff);
stimduration_str = num2str(CSSparams.stimduration);
radius_str = int2str(CSSparams.radius);
surrradius_str = int2str(CSSparams.surrradius);
dp_str = wimpcell2str(CSSparams.dispprefs);

% create figure

h0 = figure('Color',[0.8 0.8 0.8], 'Position',[140   307   488   400]);
settoolbar(h0,'none'); set(h0,'menubar','none');
ok_bt = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'Callback','set(gcbo,''userdata'',[1]);uiresume(gcf);', ...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[76 5 74 28], ...
        'String','OK', ...
        'Tag','Pushbutton1', ...
        'UserData',0);
can_bt = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'Callback','set(gcbo,''userdata'',[1]);uiresume(gcf);', ...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[219 5 74 28], ...
        'String','Cancel', ...
        'Tag','Pushbutton1', ...
        'UserData',0);
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'Callback','textbox(''centersurroundstim help'',help(''centersurroundstim''));', ...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[355.0000000000001 5 74 28], ...
        'String','Help', ...
        'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontSize',18, ...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[89 298 297 26], ...
        'String','New centersurround object...', ...
        'Style','text', ...
        'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[69 255 225 20], ...
        'String','[1x2] Center[x y]', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[303 260 129 19], ...
        'String',center_str, ...
        'Style','edit', ...
        'Tag','centerEdit');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[69 229 225 20], ...
        'String','[1x3] background color [r g b], each in 0..255', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[303 234 129 19], ...
        'String',bg_str, ...
        'Style','edit', ...
        'Tag','bgEdit');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[232 92.00000000000001 32 19], ...
        'String',stimduration_str, ...
        'Style','edit', ...
        'Tag','stimdurationEdit');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[69 88.00000000000001 146 20], ...
        'String','[1x1] stim duration (seconds)', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[303 209 129 19], ...
        'String',FGc_str, ...
        'Style','edit', ...
        'Tag','FGcEdit');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[69 204 225 20], ...
        'String','[1x3] center color [r g b], each in 0..255', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[69 180 225 20], ...
        'String','[1x3] surround color [r g b], each in 0..255', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[303 185 129 19], ...
        'String',FGs_str, ...
        'Style','edit', ...
        'Tag','FGsEdit');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[379 160 53 19], ...
        'String',surrradius_str, ...
        'Style','edit', ...
        'Tag','surrradiusEdit');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[201 156 121 20], ...
        'String','[1x1] surround radius', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[69 155 104 20], ...
        'String','[1x1] center radius', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[166 160 32 19], ...
        'String',radius_str, ...
        'Style','edit', ...
        'Tag','radiusEdit');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[166 139 32 19], ...
        'String',lagon_str, ...
        'Style','edit', ...
        'Tag','lagonEdit');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[69 132 95.00000000000001 20], ...
        'String','[1x1] center on lag', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[201 134 164 20], ...
        'String','[1x1] center off lag (-1 if none)', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[379 137 53 19], ...
        'String',lagoff_str, ...
        'Style','edit', ...
        'Tag','lagoffEdit');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[379 116 53 19], ...
        'String',surrlagoff_str, ...
        'Style','edit', ...
        'Tag','surrlagoffEdit');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[201 113 164 20], ...
        'String','[1x1] surr off lag (-1 if none)', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[69 111 95.00000000000001 20], ...
        'String','[1x1] surr on lag', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[166 118 32 19], ...
        'String',surrlagon_str, ...
        'Style','edit', ...
        'Tag','surrlagonEdit');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[281.0000000000001 89 79.00000000000001 20], ...
        'String','[1x1] contrast', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[400 93 32 19], ...
        'String',contrast_str, ...
        'Style','edit', ...
        'Tag','contrastEdit');
h1=uicontrol('Parent',h0,...
        'BackgroundColor',[0.8 0.8 0.8],...
        'ListboxTop',0,...
        'HorizontalAlignment','left',...
        'Position',[69 65 344 19],...
        'String','Set any displayprefs options here: example {''BGpretime'',1}',...
        'Style','text');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[69 45 344 19], ...
        'String',dp_str, ...
        'Style','edit', ...
        'Tag','dpEdit');

% check for syntax errors

error_free = 0;

sgsp = [];

while ~error_free,
	drawnow;
	uiwait(h0);

   if get(can_bt,'userdata')==1,
	error_free = 1;
   else, % it was OK

	center_str = get(findobj(h0,'tag','centerEdit'),'String');
	bg_str= get(findobj(h0,'tag','bgEdit'),'String');
	FGc_str= get(findobj(h0,'tag','FGcEdit'),'String');
	FGs_str= get(findobj(h0,'tag','FGsEdit'),'String');
	contrast_str= get(findobj(h0,'tag','contrastEdit'),'String');
	lagon_str= get(findobj(h0,'tag','lagonEdit'),'String');
	lagoff_str= get(findobj(h0,'tag','lagoffEdit'),'String');
	surrlagon_str= get(findobj(h0,'tag','surrlagonEdit'),'String');
	surrlagoff_str= get(findobj(h0,'tag','surrlagoffEdit'),'String');
        radius_str = get(findobj(h0,'tag','radiusEdit'),'String');
        surrradius_str = get(findobj(h0,'tag','surrradiusEdit'),'String');
        stimduration_str = get(findobj(h0,'tag','stimdurationEdit'),'String');
        dp_str = get(findobj(h0,'tag','dpEdit'),'String');

   so = 1; % syntax_okay;
   try, center = eval(center_str);
	catch, errordlg('Syntax error in center');so=0; end;
   try, BG = eval(bg_str);
	catch, errordlg('Syntax error in BG');so=0; end;
   try, FGc = eval(FGc_str);
	catch, errordlg('Syntax error in FGc');so=0; end;
   try, FGs = eval(FGs_str);
	catch, errordlg('Syntax error in FGs');so=0; end;
   try, contrast = eval(contrast_str);
	catch, errordlg('Syntax error in contrast');so=0; end;
   try, lagon=eval(lagon_str);
	catch, errordlg('Syntax error in lagon');so=0;end
   try, lagoff=eval(lagoff_str);
	catch, errordlg('Syntax error in lagoff');so=0;end
   try, surrlagon=eval(surrlagon_str);
	catch, errordlg('Syntax error in surrlagon');so=0;end
   try, surrlagoff=eval(surrlagoff_str);
	catch, errordlg('Syntax error in surrlagoff');so=0;end
   try, surrradius=eval(surrradius_str);
        catch, errordlg('Syntax error in surrradius');so=0;end;
   try, radius=eval(radius_str);
        catch, errordlg('Syntax error in radius');so=0;end;
   try, stimduration = eval(stimduration_str);
	catch, errordlg('Syntax error in stimduration');so=0;end;
   try, dp=eval(dp_str); 
	catch, errordlg('Syntax error in displayprefs'); so=0;end;

   if so,
	cssp= struct ( 'center',center,'BG',BG,'FGc',FGc,'FGs',FGs,'radius',radius,...
                       'surrradius',surrradius,'lagon',lagon,'lagoff',lagoff,...
                       'surrlagon',surrlagon,'surrlagoff',surrlagoff,...
                       'stimduration',stimduration,'contrast',contrast); 
	cssp.dispprefs = dp;

	[good, err] = verifycentersurroundstim(cssp);
	if ~good, errordlg(['Parameter value invalid: ' err]);
		  set(ok_bt,'userdata',0);
	else, error_free = 1; end;
   else, set(ok_bt,'userdata',0);
   end;
   end;
end;

if get(ok_bt,'userdata')==1, params = cssp; else, params = []; end;
delete(h0);

function str = wimpcell2str(theCell)
 %1-dim cells only, only chars and matricies
str = '{  ';
for i=1:length(theCell),
        if ischar(theCell{i})
                str = [str '''' theCell{i} ''', '];
        elseif isnumeric(theCell{i}),
                str = [str mat2str(theCell{i}) ', '];
        end;
end;
str = [str(1:end-2) '}'];

