function [nac] = edit_graphical(theac,arg2,arg3,fig)

%  NAC = EDIT_GRAPHICAL(AC)
%
%  Allows for graphical editing of parameters for AUTOCLUSTER AC.
%
%  EDIT_GRAPHICAL(AC,'NAME')
%
%  Allows editing of the AUTOCLUSTER object AC with name 'NAME' in the
%  main workspace.
%
%  See also:  MULTIEXTRACTOR, EXTRACTOR
%
%  Jan 2002, Alexander Heimel
%  based on ????, Stephen Van Hooser



nac = theac;


name = '';
if nargin<=2,
    isname = 0;
    ac = theac;
    if nargin==2,
      try,
	isname = 1;
        if ischar(arg2),
          name=arg2;
  	  ac=evalin('base',name);
	  if ~strcmp(class(ac),'autocluster'),
		error([name ' is not an autocluster.']); end;
        elseif isstruct(arg2),
          isname = 1; name = arg2.name; 
          ac = evalin('base',name);
	  if ~strcmp(class(ac),'autocluster'),
		error([name ' is not an autocluster.']); end;
        elseif isa(arg2,'cksdirstruct'),
          isname = 0; 
        end;
      catch, error(lasterr); end;
    end;
    z = geteditor('extracttool');
    params=buildwindow(ac,isname,~isempty(z),name);
    if ~isname
	if isempty(params), nac = theac;
	else, nac = autocluster(params); end;
    end;
else, % manage the command (arg3)
	if nargin==4, theFig = fig; else, theFig = gcbf; end;
	estruct = get(theFig,'userdata');
	switch(arg3),
		case 'OK',
			p = checkinput(theFig);
			if ~isempty(p),
				nac = autocluster(p);
				assignin('base',estruct.acname,nac);
				delete(theFig);
			end;
		case 'Apply',
			p = checkinput(theFig);
			if ~isempty(p),
				nac = autocluster(p);
				assignin('base',estruct.acname,nac);
			end;
		case 'Cancel',
			delete(theFig);
	end;
end;






function pstruct = checkinput(h0);
ud = get(h0,'UserData');
so = 1; % syntax ok
%try,t1=eval(get(findobj(h0,'Tag','thresh'),'String'));catch,errordlg('Syntax error in thresh.');so=0;end;
if so,
  pstruct= struct('spikewin',250e-6,...
    'usepcas',str2num(get(findobj(h0,'Tag','usepcas'),'String')), ...
    'usecumsumpcas',str2num(get(findobj(h0,'Tag','usecumsumpcas'),'String')), ...
    'usemaxs',get(findobj(h0,'Tag','usemaxs'),'Value'), ...
    'usemins',get(findobj(h0,'Tag','usemins'),'Value'), ...
    'uselocmaxs',get(findobj(h0,'Tag','uselocmaxs'),'Value'), ...
    'uselocmins',get(findobj(h0,'Tag','uselocmins'),'Value'), ...
    'max_duration',str2num(get(findobj(h0,'Tag','max_duration'),'String')), ...
    'max_n_tries',str2num(get(findobj(h0,'Tag','max_n_tries'),'String')), ...
    'rel_delta_range',str2num(get(findobj(h0,'Tag','rel_delta_range'),'String')), ...
    'n_save',2, 'n_data',0,  ...
    'force_new_search_p','true',...
    'minprob',0.99,...
    'output_object',1  );
  [good,err]=verifyautocluster(pstruct);
  if ~good, errordlg(['Error in parameters: ' err]); pstruct = []; end;
  else, pstruct = [];
end;



function p = buildwindow(ac,isname,hasdata,thename)

params = getparameters(ac);

x=20;
dy=22;

h0 = figure('Color',[0.8 0.8 0.8], ...
	'MenuBar','none', ...
	'PaperPosition',[18 180 376 432], ...
	'PaperUnits','points', ...
	'Position',[10 10 240 517]); %x y 717 303
	settoolbar(h0,'none');
h19= uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',17, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[16 475 185 19], ...
	'String','Autocluster', ...
	'Style','text', ...
	'Tag','StaticText1');



dx=200;
y=400;
h18= uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'Position',[x y+30 70 19], ...
	'String','Features', ...
	'Style','text', ...
	'Tag','StaticText1');

%featureframe
h17= uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[x-10 y-170 dx+20 200], ...
	       'String', 'Features',...
	'Style','frame', ...
	'Tag','frame');


%usepcas
h18       = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[x y 30 21], ...
	'String',params.usepcas, ...
	'Style','edit', ...
	'Tag','usepcas');
h17= uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[x+30 y dx-30 16], ...
	'String','number of PCs to use', ...
	'Style','text', ...
	'Tag','StaticText2');
y=y-dy;

%usecumsumpcas
h16       = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[x y 30 21], ...
	'String',params.usecumsumpcas, ...
	'Style','edit', ...
	'Tag','usecumsumpcas');
h15= uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[x+30 y dx-30 16], ...
	'String','number of PCs of integrated signal', ...
	'Style','text', ...
	'Tag','StaticText2');
y=y-dy;

%usemaxs
h14= uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[x y dx 20], ...
        'Value',params.usemaxs, ...
	'Style','checkbox', ...
	       'String','Use absolute maximum',...
	'Tag','usemaxs');
y=y-dy;
%usemins
h13= uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[x y dx 20], ...
        'Value',params.usemins, ...
	'Style','checkbox', ...
	       'String','Use absolute minimum',...
	'Tag','usemins');

y=y-dy;
%uselocmaxs
h12= uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[x y dx 20], ...
        'Value',params.uselocmaxs, ...
	'Style','checkbox', ...
	       'String','Use location maximum',...
	'Tag','uselocmaxs');
y=y-dy;
%uselocmins
h11= uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[x y dx 20], ...
        'Value',params.uselocmins, ...
	'Style','checkbox', ...
	       'String','Use location minimum',...
	'Tag','uselocmins');




y=150;
h10= uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'Position',[x y+30 70 19], ...
	'String','Features', ...
	'Style','text', ...
	'Tag','StaticText1');

%autoclassframe
h9 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[x-10 y-100 dx+20 130], ...
	       'String', 'Features',...
	'Style','frame', ...
	'Tag','frame');

%maxduration
h8 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[x y 30 21], ...
	'String',params.max_duration, ...
	'Style','edit', ...
	'Tag','max_duration');
h7 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[x+30 y dx-30 16], ...
	'String','Maximal cluster time (0 is no limit)', ...
	'Style','text', ...
	'Tag','StaticText2');
y=y-dy;
%max_n_tries
h6 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[x y 30 21], ...
	'String',params.max_n_tries, ...
	'Style','edit', ...
	'Tag','max_n_tries');
h5 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[x+30 y dx-30 16], ...
	'String','Maximal cluster tries (0 is no limit)', ...
	'Style','text', ...
	'Tag','StaticText2');
y=y-dy;
%rel_delta_range
h4 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[x y 30 21], ...
	'String',params.rel_delta_range, ...
	'Style','edit', ...
	'Tag','rel_delta_range');
h3 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[x+30 y dx-30 16], ...
	'String','Relative delta range', ...
	'Style','text', ...
	'Tag','StaticText2');
y=y-dy;

%Cancel-button
if ~isname, cancb = 'set(gcbo,''userdata'',[1]);uiresume(gcf);';
else, cancb = 'edit_graphical(autocluster(''default''),[],''Cancel'');'; end;
h2 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback',cancb, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[157 16 67 22], ...
	'String','Cancel', ...
	'Tag','Cancelbt', ...
	'UserData',0);

%Ok-button
if ~isname, okcb = 'set(gcbo,''userdata'',[1]);uiresume(gcf);';
else, okcb = 'edit_graphical(autocluster(''default''),[],''OK'');'; end;
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback',okcb,  ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[18 16 67 22], ...
	'String','OK', ...
	'Tag','OKbt', ...
	'UserData',0);

set(h0,'userdata',struct('acname',thename));

p = [];
if ~isname,
    error_free = 0;
    while(~error_free),
	drawnow;
	uiwait(h0);

	if get(findobj(h0,'Tag','Cancelbt'),'userdata')==1,
		p = [];
		error_free = 1;
	else, % it was OK
		p = checkinput(h0);
		if isempty(p), set(findobj(h0,'Tag','OKbt'),'UserData',0); else, error_free = 1; end;
	end;
    end;
    delete(h0);
end;
