function assoclist=lgnassociatelist(testname),

%  lgnassociatelist - list of associates for lgn data analysis
%
%  asclist = lgnassociatelist(testname), cell list

switch(testname),
	case 'CentSize',
		assoclist = {'Center size','Center latency test',...
		    'Center transience test','Sustained/Transient response',...
			 'Center Initial Response','Center Maintained Response',...
			 'Cent Size spontaneous','Cent Size Params','Has surround',...
			 'Center size cont','LGN ON or OFF','Center Size Curve',...
			 'Center Size Curve 1','Center Size Curve 2',...
			 'Center Size Curve All'};
	case 'ConeTest',
		assoclist = {'Cone test spont rates','Cone test stim rates',...
		    'Cone test significant firing','Center Initial Response imp',...
			'Center Maintained Response imp','Phasic-Tonic index',...
			'Peak latency','Peak firing rate','Spike density',...
			'Center early response','Center middle response',...
			'Center late response','PTI early/late','PTI early/middle',...
			'PTI middle/late','Cone test significant firing whole',...
			'Cone test spont rates whole','Cone test stim rates whole',...
			'Cone test ind. data0','Cone test ind. data','Pure monochrome',...
			'Center PSTH','Maintained/Initial Response Ratio',...
			'Maintained/Initial Response Ratio Positive','PTI Peak',...
			'Tau','Tau Peak','Initial latency','Peak firing rate CV'};
	case 'ConeTest3',
		assoclist = {'Cone test 3 spont rates','Cone test 3 stim rates',...
			'Cone test 3 significant firing','Cone test 3 spont rates whole',...
			'Cone test 3 stim rates whole',...
			'Cone test 3 significant firing whole',...
			'Cone test 3 ind. data','owner','Cone test 3 ind. data0',...
			'Pure monochrome 3','Cone weird 3'};
	case 'TF Test',
		assoclist = {'TF Response Curve F1','Max drifting grating firing',...
				'TF Pref','TF Phase'};
	case 'Contrast test',
		assoclist = {'C50','Contrast Max rate','Cgain 0-16','Cgain 16-100',...
			'Cgain 32-100','Cgain 0-32','Contrast at Max TF','CGain32Ratio',...
			'Naka-Rushton gain','Naka-Rushton max','Naka-Rushton 50',...
			'Contrast F1 1Hz','Contrast F1 4Hz','Contrast F1 8Hz','Contrast phases'};
	case 'all',
		assoclist = {};
		testlist = {'CentSize','ConeTest','TF Test','Contrast test'};
		for i=1:length(testlist),
			assoclist = cat(2,assoclist,lgnassociatelist(testlist{i}));
		end;
end;

