function fig = fig2()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load fig2

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'FileName','/home/vanhoosr/tools/matlab/NelsonLabTools/data_extraction/tempfuncs/fig2.m', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[715 530 560 420], ...
	'ResizeFcn','doresize(gcbf)', ...
	'Tag','Fig2', ...
	'ToolBar','figure', ...
	'DefaultaxesCreateFcn','plotedit(gcbf,''promoteoverlay''); ');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeHGBinObject', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeFigObjStorage', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeHGBinObject', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'HandleVisibility','off', ...
	'Tag','ScribeHGBinObject', ...
	'Visible','off');
h1 = uicontextmenu('Parent',h0, ...
	'Callback','domymenu update', ...
	'HandleVisibility','off', ...
	'Tag','ScribeAxisObjContextMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu cut', ...
	'HandleVisibility','off', ...
	'Label','Cu&t', ...
	'Tag','ScribeAxisObjCutMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu copy', ...
	'HandleVisibility','off', ...
	'Label','&Copy', ...
	'Tag','ScribeAxisObjCopyMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu paste', ...
	'HandleVisibility','off', ...
	'Label','&Paste', ...
	'Tag','ScribeAxisObjPasteMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu clear', ...
	'HandleVisibility','off', ...
	'Label','Clea&r', ...
	'Tag','ScribeAxisObjClearMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu showlegend', ...
	'HandleVisibility','off', ...
	'Label','Show Le&gend', ...
	'Separator','on', ...
	'Tag','ScribeAxisObjShowLegendMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu moveresize', ...
	'HandleVisibility','off', ...
	'Label','Unloc&k Axes Position', ...
	'Separator','on', ...
	'Tag','ScribeAxisObjMoveResizeMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu more', ...
	'HandleVisibility','off', ...
	'Label','Properties...', ...
	'Separator','on', ...
	'Tag','ScribeAxischildObjMoreMenu');
h1 = uicontextmenu('Parent',h0, ...
	'Callback','domymenu update', ...
	'HandleVisibility','off', ...
	'Tag','ScribeEditlineObjContextMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu cut', ...
	'HandleVisibility','off', ...
	'Label','Cu&t', ...
	'Tag','ScribeEditlineObjCutMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu copy', ...
	'HandleVisibility','off', ...
	'Label','&Copy', ...
	'Tag','ScribeEditlineObjCopyMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu paste', ...
	'HandleVisibility','off', ...
	'Label','&Paste', ...
	'Tag','ScribeEditlineObjPasteMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu clear', ...
	'HandleVisibility','off', ...
	'Label','Clea&r', ...
	'Tag','ScribeEditlineObjClearMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu size', ...
	'HandleVisibility','off', ...
	'Label','Line &Width', ...
	'Separator','on', ...
	'Tag','ScribeEditlineObjSizeMenu');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 0.5', ...
	'Checked','on', ...
	'HandleVisibility','off', ...
	'Label','0.5', ...
	'Tag','ScribeEditlineObjSizeMenu0.5');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 1', ...
	'HandleVisibility','off', ...
	'Label','1', ...
	'Tag','ScribeEditlineObjSizeMenu1');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 2', ...
	'HandleVisibility','off', ...
	'Label','2', ...
	'Tag','ScribeEditlineObjSizeMenu2');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 3', ...
	'HandleVisibility','off', ...
	'Label','3', ...
	'Tag','ScribeEditlineObjSizeMenu3');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 4', ...
	'HandleVisibility','off', ...
	'Label','4', ...
	'Tag','ScribeEditlineObjSizeMenu4');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 5', ...
	'HandleVisibility','off', ...
	'Label','5', ...
	'Tag','ScribeEditlineObjSizeMenu5');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 6', ...
	'HandleVisibility','off', ...
	'Label','6', ...
	'Tag','ScribeEditlineObjSizeMenu6');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 7', ...
	'HandleVisibility','off', ...
	'Label','7', ...
	'Tag','ScribeEditlineObjSizeMenu7');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 8', ...
	'HandleVisibility','off', ...
	'Label','8', ...
	'Tag','ScribeEditlineObjSizeMenu8');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 9', ...
	'HandleVisibility','off', ...
	'Label','9', ...
	'Tag','ScribeEditlineObjSizeMenu9');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu size 10', ...
	'HandleVisibility','off', ...
	'Label','10', ...
	'Tag','ScribeEditlineObjSizeMenu10');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu more', ...
	'HandleVisibility','off', ...
	'Label','more...', ...
	'Tag','ScribeEditlineObjSizeMenuMore');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu style', ...
	'HandleVisibility','off', ...
	'Label','Line &Style', ...
	'Tag','ScribeEditlineObjStyleMenu');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style solid', ...
	'Checked','on', ...
	'HandleVisibility','off', ...
	'Label','solid', ...
	'Tag','ScribeEditlineObjStyleMenuSolid');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style dash', ...
	'HandleVisibility','off', ...
	'Label','dash', ...
	'Tag','ScribeEditlineObjStyleMenuDash');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style dot', ...
	'HandleVisibility','off', ...
	'Label','dot', ...
	'Tag','ScribeEditlineObjStyleMenuDot');
h3 = uimenu('Parent',h2, ...
	'Callback','domymenu style dashdot', ...
	'HandleVisibility','off', ...
	'Label','dash-dot', ...
	'Tag','ScribeEditlineObjStyleMenuDashDot');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu color', ...
	'HandleVisibility','off', ...
	'Label','Color...', ...
	'Tag','ScribeEditlineObjColorMenu');
h2 = uimenu('Parent',h1, ...
	'Callback','domymenu more', ...
	'HandleVisibility','off', ...
	'Label','Properties...', ...
	'Separator','on', ...
	'Tag','ScribeEditlineObjMoreMenu');
h1 = axes('Parent',h0, ...
	'CameraUpVector',[0 1 0], ...
	'Color','none', ...
	'ColorOrder',mat1, ...
	'CreateFcn','', ...
	'HandleVisibility','off', ...
	'HitTest','off', ...
	'Position',[0 0 1 1], ...
	'Tag','ScribeOverlayAxesActive', ...
	'Visible','off', ...
	'XColor',[0.8 0.8 0.8], ...
	'XLimMode','manual', ...
	'XTickMode','manual', ...
	'YColor',[0.8 0.8 0.8], ...
	'YLimMode','manual', ...
	'YTickMode','manual', ...
	'ZColor',[0 0 0]);
h2 = text('Parent',h1, ...
	'Color',[0.8 0.8 0.8], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.4991055456171735 -0.01670644391408122 9.160254037844386], ...
	'VerticalAlignment','cap', ...
	'Visible','off');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0.8 0.8 0.8], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.01073345259391771 0.4964200477326968 9.160254037844386], ...
	'Rotation',90, ...
	'VerticalAlignment','baseline', ...
	'Visible','off');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',[-0.001788908765652952 0.9976133651551312 9.160254037844386], ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',mat2, ...
	'VerticalAlignment','bottom', ...
	'Visible','off');
set(get(h2,'Parent'),'Title',h2);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.701960784313725 0.701960784313725 0.701960784313725], ...
	'Callback','cllist = [cllist; get(2,''userdata'')];', ...
	'ListboxTop',0, ...
	'Position',[44.18614665354331 34.5804625984252 86.45115649606299 19.21136811023622], ...
	'String','Add to list', ...
	'Tag','Pushbutton1');
if nargout > 0, fig = h0; end
