function [nme] = edit_graphical(theme,arg2,arg3,fig)

%  NME = EDIT_GRAPHICAL(ME)
%
%  Allows for graphical editing of parameters for MULTIEXTRACTOR ME.
%
%  EDIT_GRAPHICAL(ME,'NAME')
%
%  Allows editing of the MULTIEXTRACTOR object ME with name 'NAME' in the main
%  workspace.
%
%  EDIT_GRAPHICAL(ME,CKSDIRSTRUCT)
%  Allows editing of ME.  When the user selects "Select Data", then the user is
%  prompted to select data from the CKSDIRSTRUCT.
%
%  EDIT_GRAPHICAL(ME,STRUCT.NAME,STRUCT.CKSDIRSTRUCT)
%  Combines the above two methods of calling.
%
%  See also:  MULTIEXTRACTOR

nme = theme;
%return;

name = '';cksds=[];
if nargin<=2,
    isname = 0;
    me = theme;
    if nargin==2,
      try,
	isname = 1;
        if ischar(arg2),
          name=arg2;
  	  me=evalin('base',name);
	  if ~strcmp(class(me),'multiextractor'),
		error([name ' is not a multiextractor.']); end;
        elseif isstruct(arg2),
          isname = 1; name = arg2.name; cksds = arg2.cksdirstruct;
          me = evalin('base',name);
	  if ~strcmp(class(me),'multiextractor'),
		error([name ' is not a multiextractor.']); end;
        elseif isa(arg2,'cksdirstruct'),
          isname = 0; cksds = arg2;
        end;
      catch, error(lasterr); end;
    end;
    z = geteditor('extracttool');
    params=buildwindow(me,isname,~isempty(z),name,cksds);
    if ~isname
	if isempty(params), nme = theme;
	else, nme = multiextractor(params); end;
    end;
else, % manage the command (arg3)
	if nargin==4, theFig = fig; else, theFig = gcbf; end;
	estruct = get(theFig,'userdata');
	switch(arg3),
		case 'OK',
			p = checkinput(theFig);
			if ~isempty(p),
				nme = multiextractor(p);
				assignin('base',estruct.mename,nme);
				delete(theFig);
			end;
		case 'Apply',
			p = checkinput(theFig);
			if ~isempty(p),
				nme = multiextractor(p);
				assignin('base',estruct.mename,nme);
			end;
		case 'Cancel',
			delete(theFig);
		case 'BrowseData',
                        ud = get(theFig,'userdata');
                        p = checkinput(theFig);
                        p = browse_data(multiextractor(p),ud.cksds);
                        if ~isempty(p), 
	                        updatefields(theFig,p);
                        end;
	end;
end;

function updatefields(h0,params)

filtmethval = params.filtermethod + 1;
filtargstr = mat2str(params.filterarg);
threshstr = mat2str(params.thresh);
thresh2str = mat2str(params.thresh2);
thresh3str = mat2str(params.thresh3);
threshcovstr = mat2str(params.threshcov);
normalizeval = params.normalize + 1;
datadirval = params.datadir + 1;
oversamplingstr = num2str(params.oversampling);
pre_timestr = mat2str(params.pre_time);
post_timestr = mat2str(params.post_time);
remove_unresolvedval = params.remove_unresolved + 1;
peak_sepstr = mat2str(params.peak_sep);
overlap_sepstr = mat2str(params.overlap_sep);
event_sepstr = mat2str(params.event_sep);
scratchfilestr = params.scratchfile;
event_type_stringstr = params.event_type_string;
output_obj_val = params.output_object + 1;
useabsval = params.useabs + 1;

set(findobj(h0,'tag','thresh'),'String',threshstr);
set(findobj(h0,'tag','thresh2'),'String',thresh2str);
set(findobj(h0,'tag','thresh3'),'String',thresh3str);
set(findobj(h0,'tag','threshcov'),'String',threshcovstr);
set(findobj(h0,'tag','directionmenu'),'value',datadirval);
set(findobj(h0,'tag','outputtypemenu'),'value',output_obj_val);
set(findobj(h0,'tag','filtertypemenu'),'value',filtmethval);
set(findobj(h0,'tag','filterarg'),'String',filtargstr);
set(findobj(h0,'tag','remove_unresolvedmenu'),'value',remove_unresolvedval);
set(findobj(h0,'tag','useabsmenu'),'value',useabsval);
set(findobj(h0,'tag','normalizemenu'),'value',normalizeval);
set(findobj(h0,'tag','oversampling'),'String',oversamplingstr);
set(findobj(h0,'tag','peak_sep'),'String',peak_sepstr);
set(findobj(h0,'tag','post_time'),'String',post_timestr);
set(findobj(h0,'tag','pre_time'),'String',pre_timestr);
set(findobj(h0,'tag','event_sep'),'String',event_sepstr);
set(findobj(h0,'tag','overlap_sep'),'String',overlap_sepstr);
set(findobj(h0,'Tag','scratchfile'),'String',scratchfilestr);
set(findobj(h0,'Tag','event_type_string'),'String',event_type_stringstr);

function p = buildwindow(wd,isname,hasdata,thename,cksds)

%str = which('multiextractor');
%[p,n]=fileparts(str);
%eval(['load ' p filesep 'edgraph ']);

params = getparameters(wd);

filtmethval = params.filtermethod + 1;
filtargstr = mat2str(params.filterarg);
threshstr = mat2str(params.thresh);
thresh2str = mat2str(params.thresh2);
thresh3str = mat2str(params.thresh3);
threshcovstr = mat2str(params.threshcov);
normalizeval = params.normalize + 1;
datadirval = params.datadir + 1;
oversamplingstr = num2str(params.oversampling);
pre_timestr = mat2str(params.pre_time);
post_timestr = mat2str(params.post_time);
remove_unresolvedval = params.remove_unresolved + 1;
peak_sepstr = mat2str(params.peak_sep);
overlap_sepstr = mat2str(params.overlap_sep);
event_sepstr = mat2str(params.event_sep);
scratchfilestr = params.scratchfile;
event_type_stringstr = params.event_type_string;
output_obj_val = params.output_object + 1;
useabsval = params.useabs + 1;

h0 = figure('Color',[0.8 0.8 0.8], ...
	'MenuBar','none', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[717 303 403 517]);
	settoolbar(h0,'none');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[16 461.0000000000001 185 19], ...
	'String','Multiextractor editor:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[15 395 178 16], ...
	'String','Thresh1 (peak detection threshold):', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[15 373 176 14], ...
	'String','Thresh2 (secondary peak threshold):', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[259 394 120 21], ...
	'String',threshstr, ...
	'Style','edit', ...
	'Tag','thresh');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[259 370 120 21], ...
	'String',thresh2str, ...
	'Style','edit', ...
	'Tag','thresh2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Min',1, ...
	'Position',[105 216 90 19], ...
	'String',{'0','-','+'},...
	'Style','popupmenu', ...
	'Tag','directionmenu', ...
	'Value',datadirval);
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[17 216 64 17], ...
	'String','Direction:', ...
	'Style','text', ...
	'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','edit_graphical(multiextractor(''default''),[],''BrowseData'');', ...
	'ListboxTop',0, ...
	'Position',[15 113 71 20], ...
	'String','Browse data', ...
	'Tag','browsedatabt');
if ~isa(cksds,'cksdirstruct'), set(h1,'enable','off'); end;
if ~isname, okcb = 'set(gcbo,''userdata'',[1]);uiresume(gcf);';
else, okcb = 'edit_graphical(multiextractor(''default''),[],''OK'');'; end;
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback',okcb, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[18 16 67 22], ...
	'String','OK', ...
	'Tag','OKbt', ...
	'UserData',0);
if ~isname, cancb = 'set(gcbo,''userdata'',[1]);uiresume(gcf);';
else, cancb = 'edit_graphical(multiextractor(''default''),[],''Cancel'');'; end;
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback',cancb, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[157 16 67 22], ...
	'String','Cancel', ...
	'Tag','Cancelbt', ...
	'UserData',0);
if isname,enstr = 'on'; else, enstr = 'off'; end;
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','edit_graphical(multiextractor(''default''),[],''Apply'');', ...
	'Enable',enstr, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[88.00000000000001 16 67 22], ...
	'String','Apply', ...
	'Tag','ApplyBt');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[229 16 67 22], ...
	'String','Help', ...
	'Tag','HelpBt');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[87.00000000000001 63 120 21], ...
	'Style','edit', ...
	'String',scratchfilestr,...
	'Tag','scratchfile');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[16 65 67 14], ...
	'String','scratchfile:', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[215 67 67 14], ...
	'String','event type:', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[290 63 112 21], ...
	'String',event_type_stringstr, ...
	'Style','edit', ...
	'Tag','event_type_string');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[16 43 78.00000000000001 17], ...
	'String','output type:', ...
	'Style','text', ...
	'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Max',2, ...
	'Min',1, ...
	'Position',[102 43 92 19], ...
	'String',{'cksmultiunit','ckssingleunit'}, ...
	'Style','popupmenu', ...
	'Tag','outputtypemenu', ...
	'Value',output_obj_val);
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Max',3, ...
	'Min',1, ...
	'Position',[95.00000000000001 439 89 19], ...
	'String',{'none','convolution','Chebyshev I'}, ...
	'Style','popupmenu', ...
	'Tag','filtertypemenu', ...
	'Value',filtmethval);
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[14 439 76 17], ...
	'String','Filter method:', ...
	'Style','text', ...
	'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[189 439 71 17], ...
	'String','Arg:', ...
	'Style','text', ...
	'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
        'Max',2,...
	'Position',[245 438 85 19], ...
	'String',filtargstr, ...
	'Style','edit', ...
	'Tag','filterarg');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[77 164 120 21], ...
	'String',pre_timestr, ...
	'Style','edit', ...
	'Tag','pre_time');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[259 347 120 21], ...
	'String',thresh3str, ...
	'Style','edit', ...
	'Tag','thresh3');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[15 162 55.00000000000001 19], ...
	'String','Pre-time:', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[15 348 192 16], ...
	'String','Thresh3 (unresolvable spike thresh):', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[208 221 103 17], ...
	'String','Remove unresolved?', ...
	'Style','text', ...
	'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Max',2,...
	'Min',1, ...
	'Position',[319 222 69 19], ...
	'String',{'no','yes'}, ...
	'Style','popupmenu', ...
	'Tag','remove_unresolvedmenu', ...
	'Value',remove_unresolvedval);
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[210 245 75 17], ...
	'String','Use abs value:', ...
	'Style','text', ...
	'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Min',1, ...
	'Position',[295 247 90 19], ...
	'String',{'no','yes'}, ...
	'Style','popupmenu', ...
	'Tag','useabsmenu', ...
	'Value',useabsval);
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[15 244 64 17], ...
	'String','Normalizing:', ...
	'Style','text', ...
	'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Min',1, ...
	'Position',[103 244 90 19], ...
	'String',{'none','std dev','cov'}, ...
	'Style','popupmenu', ...
	'Tag','normalizemenu', ...
	'UserData','[ ]', ...
	'Value',normalizeval);
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[126 140 69 19], ...
	'String',oversamplingstr, ...
	'Style','edit', ...
	'Tag','oversampling');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[16 139 103 17], ...
	'String','Oversampling:', ...
	'Style','text', ...
	'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[16 324 239 16], ...
	'String','Threshcov (ID''s spiking vs. non-spiking):', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[260 323.0000000000001 120 21], ...
	'String',threshcovstr, ...
	'Style','edit', ...
	'Tag','threshcov');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[14 417 117 15], ...
	'String','Detection parameters:', ...
	'Style','text', ...
	'Tag','StaticText4');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[20 294 64 19], ...
	'String','peak_sep:', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[91 296.0000000000001 90 21], ...
	'String',peak_sepstr, ...
	'Style','edit', ...
	'Tag','peak_sep');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[271 166 120 21], ...
	'String',post_timestr, ...
	'Style','edit', ...
	'Tag','post_time');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[209 164 59.00000000000001 19], ...
	'String','Post-time:', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[201 296.0000000000001 59.00000000000001 19], ...
	'String','event_sep:', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[277 297 90 21], ...
		'String',event_sepstr, ...
	'Style','edit', ...
	'Tag','event_sep');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[11 193 230 15], ...
	'String','Spike waveform extraction parameters:', ...
	'Style','text', ...
	'Tag','StaticText4');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[9 89 230 15], ...
	'String','Experiment variable output parameters:', ...
	'Style','text', ...
	'Tag','StaticText4');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[93 273 90 21], ...
	'String',overlap_sepstr, ...
	'Style','edit', ...
	'Tag','overlap_sep');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[16 272 70.00000000000001 19], ...
	'String','overlap_sep:', ...
	'Style','text', ...
	'Tag','StaticText2');

set(h0,'userdata',struct('browsewind',[],'mename',thename,'cksds',cksds));

p = [];
if ~isname,
    error_free = 0;
    while(~error_free),
	drawnow;
	uiwait(h0);

	if get(findobj(h0,'Tag','Cancelbt'),'userdata')==1,
		p = [];
		error_free = 1;
	else, % it was OK
		p = checkinput(h0);
		if isempty(p), set(findobj(h0,'Tag','OKbt'),'UserData',0); else, error_free = 1; end;
	end;
    end;	
    estruct=get(h0,'userdata');
    if ~isempty(estruct.browsewind)&ishandle(estruct.browsewind),
	delete(estruct.browsewind);
    end;
    delete(h0);
end;

function pstruct = checkinput(h0);
ud = get(h0,'UserData');
so = 1; % syntax ok
try,t1=eval(get(findobj(h0,'Tag','thresh'),'String'));catch,errordlg('Syntax error in thresh.');so=0;end;
try,t2=eval(get(findobj(h0,'Tag','thresh2'),'String'));catch,errordlg('Syntax error in thresh2.');so=0;end;
try,t3=eval(get(findobj(h0,'Tag','thresh3'),'String'));catch,errordlg('Syntax error in thresh3.');so=0;end;
try,t4=eval(get(findobj(h0,'Tag','threshcov'),'String'));catch,errordlg('Syntax error in threshcov.');so=0;end;
try,fa=eval(get(findobj(h0,'Tag','filterarg'),'String'));catch,errordlg('Syntax error in filter arg.');so=0;end;
try,os=eval(get(findobj(h0,'Tag','oversampling'),'String'));catch,errordlg('Syntax error in oversampling.');so=0;end;
try,prt=eval(get(findobj(h0,'Tag','pre_time'),'String'));catch,errordlg('Syntax error in pre_time.');so=0;end;
try,pst=eval(get(findobj(h0,'Tag','post_time'),'String'));catch,errordlg('Syntax error in post_time.');so=0;end;
try,pk=eval(get(findobj(h0,'Tag','peak_sep'),'String'));catch,errordlg('Syntax error in peak_sep.');so=0;end;
try,ev=eval(get(findobj(h0,'Tag','event_sep'),'String'));catch,errordlg('Syntax error in event_sep.');so=0;end;
try,ol=eval(get(findobj(h0,'Tag','overlap_sep'),'String'));catch,errordlg('Syntax error in overlap_sep.');so=0;end;
try,eval(['a_' get(findobj(h0,'Tag','scratchfile'),'String') '_1 = 5;']);
    catch,errordlg('Syntax error in scratchfile.');so=0;end;
try,eval(['a_' get(findobj(h0,'Tag','event_type_string'),'String') '_1 = 5;']);
    catch,errordlg('Syntax error in event type.');so=0;end;
if so,
	pstruct=struct('filtermethod',get(findobj(h0,'Tag','filtertypemenu'),'value')-1,...
			'filterarg',fa,...
			'thresh',t1,'thresh2',t2,...
                        'thresh3',t3,'threshcov',t4,...
                        'oversampling',os,'pre_time',prt,'post_time',pst,'peak_sep',pk,'event_sep',ev,...
                        'overlap_sep',ol,...
                        'useabs',get(findobj(h0,'Tag','useabsmenu'),'value')-1,...
                        'datadir',get(findobj(h0,'Tag','directionmenu'),'value')-1,...
                        'remove_unresolved',get(findobj(h0,'Tag','remove_unresolvedmenu'),'value')-1,...
                        'normalize',get(findobj(h0,'Tag','normalizemenu'),'value')-1,...
			'scratchfile',get(findobj(h0,'Tag','scratchfile'),'String'),...
			'event_type_string',get(findobj(h0,'Tag','event_type_string'),'String'),...
			'output_object',get(findobj(h0,'Tag','outputtypemenu'),'value')-1);
	[good,err]=verifymultiextractor(pstruct);
	if ~good, errordlg(['Error in parameters: ' err]); pstruct = []; end;
else, pstruct = [];
end;

function h0 = makebrowsedata(parentFig,threshmethod,thresh1,thresh2,wd)

co=[0 0 1;0 0.5 0;1 0 0;0 0.75 0.75;0.75 0 0.75;0.75 0.75 0;0.25 0.25 0.25];
h0 = figure('Color',[0.8 0.8 0.8], ...
        'PaperPosition',[18 180 576 432], ...
        'PaperUnits','points', ...
        'Position',[484 123 689 488], ...
        'Tag','BrowseData');
		settoolbar(h0,'none');
cb = ['edit_graphical(multiextractor(''default''),[],''BDok'',' ...
      'getfield(get(gcbf,''userdata''),''parentFig''));'];
okbt = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontSize',12, ...
        'ListboxTop',0, ...
        'Position',[420 23.2 68.8 22.4], ...
        'String','OK', ...
        'Tag','Pushbutton1','Callback',cb);
cb = ['edit_graphical(multiextractor(''default''),[],''BDcan'',' ...
      'getfield(get(gcbf,''userdata''),''parentFig''));'];
canbt = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontSize',12, ...
        'ListboxTop',0, ...
        'Position',[497.6 24.8 68.8 22.4], ...
        'String','Cancel', ...
        'Tag','Pushbutton1','Callback',cb);
cb = ['edit_graphical(multiextractor(''default''),[],''BDthreshmeth'',' ...
      'getfield(get(gcbf,''userdata''),''parentFig''));'];
threshmethodpopup = uicontrol('Parent',h0, ...
        'Units','points', ...
        'ListboxTop',0, ...
        'Min',1, ...
        'Position',[495.6 332 100 20], ...
        'String',{'N std devs', 'Absolute'}, ...
        'Style','popupmenu', ...
        'Tag','PopupMenu1', ...
        'BackgroundColor',[0.8 0.8 0.8],...
        'Value',threshmethod,'Callback',cb,'userdata',threshmethod);
cb = ['edit_graphical(multiextractor(''default''),[],''BDupdate'',' ...
      'getfield(get(gcbf,''userdata''),''parentFig''));'];
thresh1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[495.6 292 100 17.6], ...
        'Style','edit', ...
        'Tag','EditText1','String',thresh1,'Callback',cb);
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[495.6 356.8 100 13.6], ...
        'String','Thresh method:', ...
        'Style','text', ...
        'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[495.6 314.4 100 13.6], ...
        'String','Thresh1:', ...
        'Style','text', ...
        'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[495.6 257.6 100 13.6], ...
        'String','Thresh2:', ...
        'Style','text', ...
        'Tag','StaticText1');
cb = ['edit_graphical(multiextractor(''default''),[],''BDupdate'',' ...
      'getfield(get(gcbf,''userdata''),''parentFig''));'];
thresh2 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[495.6 234.4 100 18.4], ...
        'Style','edit', ...
        'Tag','EditText1','String',thresh2,'Callback',cb);
dataax = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',co, ...
        'Position',[35 247 459 166], ...
        'Tag','Axes1', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
stddevstr = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[495.6 193.6 100 16.8], ...
        'String','Std dev:', ...
        'Style','text', ...
        'Tag','StaticText2');
histax = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',co, ...
        'Position',[37 40 164 153], ...
        'Tag','Axes2', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
waveax = axes('Parent',h0, ...
        'Units','pixels', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',co, ...
        'Position',[256 40 164 153], ...
        'Tag','Axes2', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
cb = ['edit_graphical(multiextractor(''default''),[],''BDthresh1set'',' ...
      'getfield(get(gcbf,''userdata''),''parentFig''));'];
thresh1set = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[495.6 273.6 100 16.8], ...
        'String','Select on graph', ...
        'Tag','Pushbutton2','Callback',cb);
cb = ['edit_graphical(multiextractor(''default''),[],''BDthresh2set'',' ...
      'getfield(get(gcbf,''userdata''),''parentFig''));'];
thresh2set = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[495.6 216.8 100 16.8], ...
        'String','Select on graph', ...
        'Tag','Pushbutton2','Callback',cb);
cb = ['edit_graphical(multiextractor(''default''),[],''BDdata'',' ...
      'getfield(get(gcbf,''userdata''),''parentFig''));'];
selectdatabt = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[430 61.6 100 23.2], ...
        'String','Select Data', ...
        'Tag','Pushbutton3','Callback',cb);
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[72 197.6 82.4 14.4], ...
        'String','Histogram', ...
        'Style','text', ...
        'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[265.6 196.8 82.4 14.4], ...
        'String','Waveforms:', ...
        'Style','text', ...
        'Tag','StaticText3');
cb = ['edit_graphical(multiextractor(''default''),[],''BDshowpeaks'',' ...
      'getfield(get(gcbf,''userdata''),''parentFig''));'];
showpeakschk = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'HorizontalAlignment','left', ...
        'Position',[495.6 166.4 100 21.6], ...
        'String','Show Peaks', ...
        'Style','checkbox', ...
        'Tag','Checkbox1','Callback',cb,'Value',1);
cb = ['edit_graphical(multiextractor(''default''),[],''BDshowpoints'',' ...
      'getfield(get(gcbf,''userdata''),''parentFig''));'];
showpointschk = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[495.6 141.6 100 21.6], ...
        'HorizontalAlignment','left', ...
        'String','Show Points', ...
        'Style','checkbox', ...
        'Tag','Checkbox1','Callback',cb);
cb = ['edit_graphical(multiextractor(''default''),[],''BDshowthresh'',' ...
      'getfield(get(gcbf,''userdata''),''parentFig''));'];
showthreshchk = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[495.6 116.8 100 21.6], ...
        'HorizontalAlignment','left', ...
        'String','Show Threshes', ...
        'Style','checkbox', ...
        'Tag','Checkbox1','Value',1,'Callback',cb);
h1 = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontSize',12, ...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[16.8 400.4 220 20], ...
        'String','Windowdiscriminator data browser', ...
        'Style','text', ...
        'Tag','StaticText4');
ud2 = get(parentFig,'userdata');
set(h0,'userdata',struct('okbt',okbt,'canbt',canbt,'threshmethodpopup',...
threshmethodpopup,'thresh1',thresh1,'thresh2',thresh2,'dataax',dataax,...
'stddevstr',stddevstr,'histax',histax,'waveax',waveax,'thresh1set',...
thresh1set,'thresh2set',thresh2set,'selectdatabt',selectdatabt,'showpeakschk',...
showpeakschk,'showpointschk',showpointschk,'showthreshchk',showthreshchk,'parentFig',parentFig,...
'data',[],'wd',wd,'cksds',ud2.cksds));


