function AnalyzeExperiment(figureNum, datapath, analysispath)

%  ANALYZEEXPERIMENT(FIGURENUM, DATAPATH, ANALYSISPATH)
%
%  Note:  This file is pretty specific to the Nelson Lab at Brandeis University.
%
%  AnalyzeExperiment takes over the figure FIGURENUM, and sets up a panel to
%  control our experimental setup.  The panel should be self-explanatory,
%  but maybe we'll actually write more documentation someday.  Note that the
%  figure is totally cleared by this routine.
%
%  There are two optional arguments:  DATAPATH and ANALYSISPATH.  These provide
%  initial values for the data path and analysis path.  Otherwise, the system
%  default values are chosen.
%
%                             Questions?  vanhoosr@brandeis.edu

  % add the path of the callback function
loc = which('AnalyzeExperiment');
li = find(loc=='/'); loc = loc(1:li(end)-1);
addpath([loc '/panelcallbacks/']);

g = figure(figureNum); clf;

if nargin>1,
	InVivoDataPathRem = datapath;
	InVivoAnalysisPath = analysispath;
else,
	[Y,M,D] = datevec(date);
	InVivoDataPathRem = ['dataman:data:' sprintf('%.4i-%.2i-%.2i',Y,M,D)];
	[dummy,str] = dos('whoami');
	if dummy==0,
		str = str(1:end-1);
		InVivoAnalysisPath = ['/home/' str ...
		'/nelson/experiment_analysis/' sprintf('%.4i-%.2i-%.2i',Y,M,D)];
	else, InVivoAnalysisPath = '';
	end;
end;

 % convert from the Mac
InVivoDataPath = InVivoDataPathRem;
InVivoDataPath(find(InVivoDataPath==':'))='/';
InVivoDataPath = [ '/home/' InVivoDataPath ];
SaveDir = 't001';

ss = -360;
ds = -230;
as = 0000;

pathframe = uicontrol('Style','frame','Units','point', ...
              'Position',[10 485+ds 550 105]);

dpl = uicontrol('Style','text','String','Data path:','Units','point', ...
	'Position',[20 556+ds 125 20],'fontsize',14,'fontweight','bold', ...
	'HorizontalAlignment','left');

dp  = uicontrol('Style','edit','String',InVivoDataPathRem,'Units','point', ...
	'Position',[127 555+ds 400 25],'fontsize',14,'fontweight','normal', ...
	'HorizontalAlignment','left');

dptl= uicontrol('Style','text','String','Save dir:','Units','point', ...
	'Position',[20 523+ds 125 20],'fontsize',14,'fontweight','bold', ...
	'HorizontalAlignment','left');

dpt  = uicontrol('Style','edit','String',SaveDir,'Units','point', ...
	'Position',[127 522+ds 400 25],'fontsize',14,'fontweight','normal', ...
	'HorizontalAlignment','left');

apl = uicontrol('Style','text','String','Analysis path:','Units','point', ...
	'Position',[20 493+ds 125 20],'fontsize',14,'fontweight','bold', ...
	'HorizontalAlignment','left');

ap  = uicontrol('Style','edit','String',InVivoAnalysisPath,'Units','point', ...
	'Position',[127 492+ds 400 25],'fontsize',14,'fontweight','normal', ...
	'HorizontalAlignment','left');

acq_frame = uicontrol('Style','frame','Units','point', ...
		'Position',[10 130+as 550 110]);

aql = uicontrol('Style','text','String','Acquisition List:','Units','point',...
	'Position',[20 212+as 120 20],'fontsize',14,'fontweight','bold', ...
	'HorizontalAlignment','left');

aqa = uicontrol('Style','pushbutton','String','Add','Units','point', ...
	'Position',[150 215+as 60 20],'fontsize',14,'fontweight','bold',...
	'HorizontalAlignment','center','Callback','runexpercallbk add_aq');

aqe = uicontrol('Style','pushbutton','String','Edit','Units','point',...
	'Position',[220 215+as 60 20], 'fontsize',14,'fontweight','bold', ...
	'HorizontalAlignment','center','Callback','runexpercallbk edit_aq');

aqd = uicontrol('Style','pushbutton','String','Delete','Units','point',...
	'Position',[290 215+as 60 20],'fontsize',14,'fontweight','bold',...
	'HorizontalAlignment','center','Callback','runexpercallbk delete_aq');

aqo = uicontrol('Style','pushbutton','String','Open...','Units','point',...
	'Position',[360 215+as 60 20],'fontsize',14,'fontweight','bold',...
	'HorizontalAlignment','center','Callback','runexpercallbk open_aq');

aqs = uicontrol('Style','pushbutton','String','Save...','Units','point',...
	'Position',[430 215+as 60 20],'fontsize',14,'fontweight','bold',...
	'HorizontalAlignment','center','Callback','runexpercallbk save_aq');

aql = uicontrol('Style','listbox','String',{},'Units','point', ...
	'Position',[35 135+as 500 75],'fontweight','normal','fontsize',12,...
	'HorizontalAlignment','left','BackgroundColor',[1 1 1],'UserData',{});

scriptframe = uicontrol('Style','frame','Units','point',  ...
			'Position', [10 370+ss 550 110]);

rsdl= uicontrol('Style','text','String','Remote Dir', 'Units','point',...
	'Position',[20 449+ss 125 20],'fontsize',14,'fontweight','bold', ...
	'HorizontalAlignment','left');

rsd = uicontrol('Style','edit','String',InVivoRemoteDirPath,'Units','point',...
	'Position',[127 452+ss 400 20],'fontsize',14,'fontweight','normal',...
	'HorizontalAlignment','left');

rsl = uicontrol('Style','text','String','Run Script:','Units','point', ...
	'Position',[20 418+ss 125 20],'fontsize',14,'fontweight','bold', ...
	'HorizontalAlignment','left');

rs  = uicontrol('Style','edit','String','','Units','point', ...
	'Position',[127 420+ss 350 25],'fontsize',14,'fontweight','normal', ...
	'HorizontalAlignment','left');

rsb = uicontrol('Style','pushbutton','String','Go','Units','point', ...
	'Position',[497 420+ss 30 25],'fontsize',14,'fontweight','bold', ...
	'HorizontalAlignment','center','Callback','runexpercallbk runscript');

rssl= uicontrol('Style','text','String','Show StimScript:','Units','point', ...
	'Position',[20 383+ss 150 20],'fontsize',14,'fontweight','bold', ...
	'HorizontalAlignment','left');

swvs= uicontrol('Style','checkbox','String','Acquire Data','Units','point',...
	'Position',[360 387+ss 118 20],'fontsize',14,'fontweight','bold',...
	'HorizontalAlignment','left');

rssb= uicontrol('Style','pushbutton','String','Go','Units','point', ...
	'Position',[497 385+ss 30 25],'fontsize',14,'fontweight','bold', ...
	'HorizontalAlignment','center','Callback','runexpercallbk showstim');

rss = uicontrol('Style','edit','String','','Units','point', ...
	'Position',[140 385+ss 215 25],'fontsize',14,'fontweight','normal', ...
	'HorizontalAlignment','left');

data = struct('datapath',dp,'savedir',dpt,'analpath',ap,'runscript',rs, ...
	'remotepath',rsd,'showstim',rss,'savestims',swvs, 'list_aq',aql,...
	'add_aq',aqa,'edit_aq',aqe,'delete_aq',aqd,'open_aq',aqo,'save_aq',aqs);

set(gcf,'UserData',data);
