function params = hcprocessparams( record )
%HCPROCESSPARAMS sets parameters for headcamera analysis
%
%  To make local parameter changes, add lines to processparams_local.m
%  instead of in this file.
%
% 2022, Alexander Heimel

if nargin<1
    record = []; %#ok<NASGU>
end

params.pupil_area_min = 40; % pxl^2
params.pupil_area_max = 2700; % pxl^2 
params.default_pupil_threshold_prctile = 10; % perc
params.default_pupil_threshold = 100; % luminance [0-255]
params.default_glint_threshold = 130; % luminance [0-255]
params.glint_area_min = 20; % pxl^2
params.glint_area_max = 150; % pxl^2
params.artefact_deviation_threshold = 8; % pxl
params.artefact_warning = 0.75; % [0-1], warn when jumps this fraction of deviation threshold 
params.automatic_blinking_threshold = 0.6; % maximum similarity
params.blink_blanking_time = 0.4; %s time to blank out before and after blink
params.key_bindings = { ...
'quit',       'q', 'quit';...
'pause',      ' ', 'pause or proceed';...
'forward',    '.', 'step one frame forward';...
'backward',   ',', 'step one frame backward';...
'skipmore',   'f', 'skip more frames';...
'skipless',   's', 'skip less frames';...
'realtime',   'r', 'toggle real time display speed';...
'clear',      'x', 'clear part of analysis';...
'analyse',    'a', 'toggle analysis';...
'patches',    't', 'toggle patches';...
'pupil',      'p', 'toggle pupil outline';...
'zoom',       'z', 'toggle zoom';...
'goto',       'g', 'goto time';...
'blink',      'b', 'toggle blink';...
'label',      'l', 'toggle label';...
'incpupil',   '=', 'increase pupil threshold (increase pupil area)';...
'decpupil',   '-', 'decrease pupil threshold (decrease pupil area)';...
'incglint',   ']', 'increase glint threshold (decrease glint area)';...
'decglint',   '[', 'decrease glint threshold (increase glint area)';...
'gotomissing','m', 'goto missing pupil';...
'reset',      'y', 'toggle reset';...
}; 


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% keep at bottom
if exist('processparams_local.m','file')
    params = processparams_local( params );
end

