function newassc = ctxnewassociate(type,data,desc)
% NEWASSC = CTXNEWASSOCIATE(TYPE,DATA,DESC)
% 
% NEWASSC = ...
%    struct('type',TYPE,...
%	   'owner','protocol_CTX',...
%	   'data',DATA,...
%	   'desc',DESC);


newassc = ...
    struct('type',type,...
	   'owner','protocol_CTX',...
	   'data',data,...
	   'desc',desc);
