function fig = editdotsstim()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

h0 = figure('Color',[0.8 0.8 0.8], ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[361 392 495 499]);
try, set(h0,'ToolBar','none'); set(h0,'MenuBar','none'); end;
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','set(gcbo,''userdata'',[1]);uiresume(gcf);', ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[46 28.5 88.75 33.75], ...
	'String','OK', ...
	'Tag','OKBt', ...
	'UserData',0);
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','set(gcbo,''userdata'',[1]);uiresume(gcf);', ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[217.25 31 88.75 33.75], ...
	'String','Cancel', ...
	'Tag','CancelBt', ...
	'UserData',0);
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','textbox(''movingdotsstim help'',help(''movingdotsstim''));', ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[381 32.25 88.75 33.75], ...
	'String','Help', ...
	'Tag','HelpBt');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',18, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[64 452 356 31], ...
	'String','New movingdotsstim object...', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[40 427 270 24], ...
	'String','[1x4] Rect [top_x top_y bottom_x bottom_y]', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[323 431 155 23], ...
	'String','[0 0 100 100]', ...
	'Style','edit', ...
	'Tag','RectEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[37 403 270 24], ...
	'String','[1x3] background color [r g b], each in 0..255', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[322 408 155 23], ...
	'String','[128 128 128]', ...
	'Style','edit', ...
	'Tag','BGEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[436 325 38 23], ...
	'String','1800', ...
	'Style','edit', ...
	'Tag','DirectionEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[301 320 125 24], ...
	'String','[1x1] direction (deg)', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[43 316 145 24], ...
	'String','[1x1] velocity (deg/s)', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[223 321 64 23], ...
	'String','15', ...
	'Style','edit', ...
	'Tag','VelocityEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[38 170 430 24], ...
	'String','[35x1] randomState: use rand(''state'') or enter a variable name', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[43 142 429.0000000000001 28], ...
	'String','rand(''state'')', ...
	'Style','edit', ...
	'Tag','RandstateEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[43 84 429.0000000000001 28], ...
	'String','{}', ...
	'Style','edit', ...
	'Tag','DispprefsEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[38 111 430 24], ...
	'String','Set any displayprefs options here: example: {''BGpretime'',1}', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[322 386 155 23], ...
	'String','[128 128 128]', ...
	'Style','edit', ...
	'Tag','FGEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[37 381 270 24], ...
	'String','[1x3] dot color [r g b], each in 0..255', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[223 295 64 23], ...
	'String','15', ...
	'Style','edit', ...
	'Tag','AngvelocityEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[43 292 182 24], ...
	'String','[1x1] angular velocity (deg/s)', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[300 294 125 24], ...
	'String','[1x1] coherence [0,1]', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[435.0000000000001 299 38 23], ...
	'String','1800', ...
	'Style','edit', ...
	'Tag','CoherenceEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[43 262 182 24], ...
	'String','[1x1] dot size (deg)', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[223 266 64 23], ...
	'String','15', ...
	'Style','edit', ...
	'Tag','DotsizeEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[224 239 64 23], ...
	'String','15', ...
	'Style','edit', ...
	'Tag','NumdotsEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[44 235 182 24], ...
	'String','[1x1] number of dots', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[44 204 182 24], ...
	'String','[1x1] viewing distance (cm)', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[224 208 64 23], ...
	'String','15', ...
	'Style','edit', ...
	'Tag','DistanceEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[435.0000000000001 270 38 23], ...
	'String','1800', ...
	'Style','edit', ...
	'Tag','FpsEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[300 265 125 24], ...
	'String','[1x1] frames / second', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[300 236 125 24], ...
	'String','[1x1] duration (s)', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[435.0000000000001 241 38 23], ...
	'String','1800', ...
	'Style','edit', ...
	'Tag','DurationEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[300 236-29 125 24], ...
	'String','[1x1] num patterns', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[435.0000000000001 241-29 38 23], ...
	'String','1800', ...
	'Style','edit', ...
	'Tag','NumpatternsEdit');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[300 236-29-15 125 15], ...
	'String','[1x1] dot lifetimes', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[435.0000000000001 236-29-12 38 18], ...
	'String','1800', ...
	'Style','edit', ...
	'Tag','LifetimesEdit');
if nargout > 0, fig = h0; end
