function b = transferscripts(scriptnames,scriptlist);

%  TRANSFERSCRIPTS - Transfers scripts to remote stimulus computer
%
%  B = TRANSFERSCRIPTS(SCRIPTNAMES,SCRIPTLIST)
%
%  Accepts a cell list of script names (SCRIPTNAMES) and the variables
%  (SCRIPTLIST), and transfers them to the remote computer.  The stimuli
%  or scripts are then loaded.

NewStimGlobals;
remotecommglobals;

b = checkremotedir(Remote_Comm_dir);
if ~b, return; end;

biglist = [];
for i=1:length(scriptnames),
  eval([scriptnames{i} '=scriptlist{i};']);
  biglist = [biglist ' ''' scriptnames{i} ''','];
end;
pathn = fixpath(Remote_Comm_dir);
fname = [pathn 'toremote']; 
if ~isempty(biglist), biglist = biglist(1:end-1); end;
v = str2mat(version('-release'));
if v>13,
	biglist = [biglist ',''-V6'',''-mat'' '];
	else, biglist = [biglist ',''-mat'' '];
end;
eval(['save (fname,' biglist ');']);


strs = {      'names=load(''toremote'',''-mat'');fnames=fieldnames(names);'...
             'finished=zeros(1,length(fnames));'...
             'for i=1:length(fnames),'...
               'if exist(fnames{i})==1,'...
                 'eval([''b1=isa('' fnames{i} '', ''''stimscript'''');'']);'...
                 'eval([''b2=isa('' fnames{i} '', ''''stimulus'''');'']);'...
                 'if b1|b2,'...
                    'eval([''b3 = '' fnames{i} '' == names.'' fnames{i} '';'']);'...
                    'eval([''b3 = b3&isloaded('' fnames{i} '');'']);'...
                    'if ~b3,'...
                      'if b1,'...
                        'eval([fnames{i} '' = unloadStimScript('' fnames{i} '');'']);'...
                      'else,'...
                        'eval([fnames{i} '' = unloadstim('' fnames{i} '');'']);'...
                      'end;'...
                    'else, finished(i) = 1;'...
                    'end;'...
                 'end;'...
               'end;'...
               'if finished(i)~=1,'...
                 'eval([''b1=isa(names.'' fnames{i} '', ''''stimscript'''');'']);'...
                 'eval([''b2=isa(names.'' fnames{i} '', ''''stimulus'''');'']);'...
                 'if b1,'...
                    'eval([fnames{i} ''=loadStimScript(names.'' fnames{i} '');'']);'...
                 'elseif b2,'...
                    'eval([fnames{i} ''=loadstim(names.'' fnames{i} '');'']);'...
                 'end;'...
                 'finished(i)=1;'...
               'end;'...
             'end;'...
             'save(''gotit'',''fnames'',''-mat'');',...   
             'save(''fromremote'',''fnames'',''-mat'');'};    
                   
b = sendremotecommand(strs);
if b,
  dowait(1);
  thefig = geteditor('RemoteScriptEditor');
  if isempty(thefig), RemoteScriptEditor; else, RemoteScriptEditor('Update',thefig); end;
end;
