function parameters = default
% 2012, Alexander Heimel

parameters = struct( ...
    'imageType',         2,              ...
    'animType',          4,              ...
    'flickerType',       0,              ...
    'angle',             45,             ...
    'chromhigh',		255*[1 1 1],	...
    'chromlow',		[0 0 0],	...
    'sFrequency',        0.05,              ...
    'sPhaseShift',       0,              ...
    'distance',          15,             ...
    'tFrequency',        2,              ...
    'barWidth',          0.5,            ...
    'rect',       [200 200 400 400],     ...
    'nCycles',           10,             ...
    'contrast',          1,         		 ...
    'background',        0.5,            ...
    'backdrop',    		0.5,            ...
    'barColor',          1,              ...
    'nSmoothPixels',     2,              ...
    'fixedDur',          0,              ...
    'windowShape',       1,              ...
    'loops',             0,               ...
    'size',              NaN,             ... % diameter in degrees. If NaN, it is ignored.
    'ps_add',            ''           ...
);
parameters.dispprefs = {};
