function centersurrounds(arg)

if nargin==1,
  f = gcbf;
  if strcmp(arg,'done'), delete(f); return; end; 

  stimname = get(findobj(f,'tag','stimPopup'),'String');
  stimname = stimname{get(findobj(f,'tag','stimPopup'),'value')};
  stim = evalin('base',stimname);
  p = getparameters(stim);
  p2 = p;
  eval(['isi=' get(findobj(f,'tag','isiEdit'),'String') ';']);
  eval(['reps=' get(findobj(f,'tag','repeatsEdit'),'String') ';']);
  p2.dispprefs= {'BGpretime',isi};
  makeScript = 1;

  CSscript = stimscript(0);
  switch arg,
    case 'Varycenter',
       centsteps = eval(get(findobj(f,'tag','varycenterEdit'),'String'));
       rshifts=-centsteps(1):centsteps(2):centsteps(1);
       initcent = p.center;
       for i=1:length(rshifts),
          for j=1:length(rshifts),
             p2.center = initcent+rshifts([i j]);
             newstim = centersurroundstim(p2);
             CSscript = append(CSscript,newstim);
          end;
       end;
    case 'Varyradius',
       radvar = eval(get(findobj(f,'tag','varyradiusEdit'),'String'));
       rshifts = radvar(1):radvar(3):radvar(2);
       initrad = p.radius;
       for i=1:length(rshifts),
           p2.radius = rshifts(i);
           newstim = centersurroundstim(p2);
           CSscript = append(CSscript,newstim);
       end;
    case 'Varysurroundlag',
       eval(['vls=' get(findobj(f,'tag','varysurroundlagEdit'),'String') ';']);
       surrlags = vls(1):vls(3):vls(2);
       for i=1:length(surrlags),
           p2.surrlagon=surrlags(i);
           newstim=centersurroundstim(p2);
           CSscript = append(CSscript,newstim);
       end;
    case {'analyzeradius','analyzesurroundlag'},
       z = geteditor('RunExperiment');
       if ~isempty(z), 
          ud = get(z,'userdata'); cksds=ud.cksds; cksds=update(cksds);
          if strcmp(arg,'analyzeradius'), 
             test = get(findobj(f,'tag','varyradiusanalEdit'),'String');
          elseif strcmp(arg,'analyzesurroundlag'),
             test = get(findobj(f,'tag','varysurroundlaganalEdit'),'String');
          end;
          namerefs = getallnamerefs(cksds);
          nri = get(findobj(f,'tag','namerefPopup'),'value');
          namerefs(nri),
          try,s=getstimscripttimestruct(cksds,test); catch,errordlg('Cannot find test directory.');end;
          try,g=getcells(cksds,namerefs(nri));catch,errordlg('Cannot load cell data.');end;
          loadstr = '';for i=1:length(g),loadstr=[loadstr ', ''' g{i} '''']; end;loadstr=loadstr(2:end);
          if isempty(loadstr),errordlg('Empty data'); end;
          eval(['d = load(getexperimentfile(cksds), ' loadstr ',''-mat'');']);
          for i=1:length(g),
             inp.st=s;
             inp.spikes=getfield(d,g{i});
             if strcmp(arg,'analyzeradius'), inp.paramname='radius';
             elseif strcmp(arg,'analyzesurroundlag'),inp.paramname='surrlagon';
             end;
             inp.title=[g{i}];
             where.figure=figure;where.rect=[0 0 1 1]; where.units='normalized';
             orient(where.figure,'landscape');
             global tc;
             tc=tuning_curve(inp,'default',where);
          end;
       else, errordlg('No RunExperiment window.');   
       end;
    case 'analyzesurroundlag',

    case 'analyzecenter',
    case 'Edit',
       makeScript =0;
       evalin('base',[stimname '=centersurroundstim(''graphical'',' stimname ');']);
  end;
  if makeScript,
    CSscript=setDisplayMethod(CSscript,1,reps);
    assignin('base','CSscript',CSscript);
    UpdateNewStimEditors;
  end;
else, 

h0 = figure('Color',0.8*[1 1 1],'Tag','','MenuBar','figure',...
            'PaperPosition',[18 180 576 432], ...
            'PaperUnits','points','Position',[323   327   684   420]);
settoolbar(h0,'figure');

h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontSize',16, ...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[129 303 297 19], ...
        'String','Creates a centersurround script', ...
        'Style','text', ...
        'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[46 178 104 23], ...
        'String','Vary center', ...
        'Tag','varycenterBt','Callback','centersurrounds Varycenter');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Min',1, ...
        'Position',[50 242 93 24], ...
        'String',listofvars('centersurroundstim'), ...
        'Style','popupmenu', ...
        'Tag','stimPopup', ...
        'Value',1);
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[51 266 91 17], ...
        'String','stim to base on:', ...
        'Style','text', ...
        'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[150 242 62 24], ...
        'String','Edit', ...
        'Callback','centersurrounds Edit',...
        'Tag','stimeditBt');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[155 179 200 18], ...
        'String','From -r to r in steps:  [r step]', ...
        'Style','text', ...
        'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[380 179 125 21], ...
        'String','[100 10]', ...
        'Style','edit', ...
        'Tag','varycenterEdit');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[510 179 75 21], ...
        'String','', ...
        'Style','edit', ...
        'Tag','varycenteranalEdit');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',0.8*[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[510 200 75 21], 'Fontweight','bold',...
        'String','test', ...
        'Style','text');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',0.8*[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[590 179 60 21], ...
        'String','Analyze', 'fontweight','bold',...
        'Tag','varycenteranalBt','Callback','centersurroundstims analyzecenter');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[380 153 125 21], ...
        'String','[5 100 5]', ...
        'Style','edit', ...
        'Tag','varyradiusEdit');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',0.8*[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[590 153 60 21], ...
        'String','Analyze', 'FontWeight','bold',...
        'Tag','varyradiusanalBt','Callback','centersurrounds analyzeradius');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[510 153 75 21], ...
        'String','', ...
        'Style','edit', ...
        'Tag','varyradiusanalEdit');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[155 150 200 18], ...
        'String','From r0 to r1 in steps:  [r0 r1 step]', ...
        'Style','text', ...
        'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[46 148 104 23], ...
        'String','Vary radius', ...
        'Tag','varyradiusBt','Callback','centersurrounds Varyradius');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[243 262 120 20], ...
        'String','interstim-interval:', ...
        'Style','text', 'HorizontalAlignment','left',...
        'Tag','StaticText4');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, 'HorizontalAlignment','left',...
        'Position',[243 233 65 20], ...
        'String','Repeats:', ...
        'Style','text', ...
        'Tag','StaticText4');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[380 236 100 21], ...
        'String','10', ...
        'Style','edit', ...
        'Tag','repeatsEdit');
h1 = uicontrol('Parent',h0,...
        'BackgroundColor',0.8*[1 1 1],...
        'ListboxTop',0,...
        'Position',[580 236 100 21], ...
        'Style','popupmenu', 'String',' ','Tag','namerefPopup');
h1 = uicontrol('Parent',h0,...
        'BackgroundColor',0.8*[1 1 1],...
        'ListboxTop',0,...
        'Position',[480 233 100 21], ...
        'Style','text', 'String','Nameref:','Tag','');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[380 261 100 23], ...
        'String','[0.5]', ...
        'Style','edit', ...
        'Tag','isiEdit');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[46 118 104 23], ...
        'String','Vary surround lag', ...
        'Tag','varysurroundlagBt','Callback','centersurrounds Varysurroundlag');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'ListboxTop',0, ...
        'Position',[154 120 200 18], ...
        'String','From t0 to t1 in steps:  [t0 t1 step]', ...
        'Style','text', ...
        'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[380 122 125 21], ...
        'String','[-0.100 0.100 0.050]', ...
        'Style','edit', ...
        'Tag','varysurroundlagEdit');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[510 122 75 21], ...
        'String','', ...
        'Style','edit', ...
        'Tag','varysurroundlaganalEdit');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',0.8*[1 1 1], ...
        'ListboxTop',0, ...
        'Position',[590 122 60 21], ...
        'String','Analyze', 'FontWeight','bold', ...
        'Tag','varysurroundlaganalBt','Callback','centersurrounds analyzesurroundlag');
h1 = uicontrol('Parent',h0, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'FontWeight','bold', ...
        'ListboxTop',0, ...
        'Position',[220 51 96 20], ...
        'String','Done', 'Callback','centersurrounds done',...
        'Tag','doneBt');
z = geteditor('RunExperiment');
if ~isempty(z),
  ud=get(z,'userdata'); cksds=ud.cksds; nrs={'none'}; nr=getallnamerefs(cksds);
  for i=1:length(nr), nrs{i}=[nr(i).name ' | ' int2str(nr(i).ref) ]; end;
  set(findobj(h0,'tag','namerefPopup'),'String',nrs);
end;

end;
