figure(1)
  i__ = 1;
for i=interval,
  subplot(10,10,i__);
  plotcsp(csp(:,i));
  LL=stime(idx(i));
  LLL=int2str(LL);
  title([LLL ':' int2str(stype(idx(i)))]);% ':' int2str(idx(i))]);
  set(gca,'xtick',[]);
     %'set(get(get(2,''Children''),''title''),''String'',int2str(idx(i)));' ...
     %'set(get(get(3,''Children''),''title''),''String'',int2str(idx(i)));' ...
  set(gca,'ButtonDownFcn',...
   ['set(get(2,''Children''),''xlim'',' LLL '+[-100 100],''ylim'',[-4 2]);' ...
  'set(get(3,''Children''),''xlim'',' LLL '+[-100 100],''ylim'',[-1 300]);' ...
  'if exist(''bar1'')&ishandle(bar1),delete(bar1);end;if exist(''bar2'')&ishandle(bar2),delete(bar2);end;' ...
  'axes(get(2,''Children''));bar1=plot([' LLL ' ' LLL '],[-4 2],''k'');' ...
  'axes(get(3,''Children''));bar2=plot([' LLL ' ' LLL '],[-1 300],''k'');']);
  i__ = i__ + 1;
end;

