function NeuralAnalysisObjectInit

pwd = which('NeuralAnalysisObjectInit');

pi = find(pwd==filesep); pwd = [pwd(1:pi(end)-1) filesep];

addpath(pwd,...
    fullfile(pwd,'MeasuredData'),...
    fullfile(pwd,'Analyses_objects'),...
    fullfile(pwd,'Analyses_routines'),...
    fullfile(pwd,'Analyses_routines' , 'periodicstim_continuous'),...
    fullfile(pwd,'general'),...
    fullfile(pwd,'UtilityProcs'),...
    fullfile(pwd,'data_extraction'),...
    fullfile(pwd,'data_extraction' , 'tempfuncs'),...
    fullfile(pwd,'data_extraction' , 'spike2cell'),...    
    fullfile(pwd,'DataManagement'))

windowdiscriminator('default');
cksmultipleunit([1 2],'','',1.5,[]);
wdcluster('default');
multiextractor('default');
dotdiscriminator('default');

g = measureddata([1 2],'','');
g = spikedata([1 2],'','');
